### ISSUE TITLE
Metadata: Add dropdown list for "Corporate Group"

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#132] opened 2015-07-10 21:45 UTC
This shall have a picklist, which might be generated by NRGI in a separate repository. 

This issue will await the appropriate solution which is being developed for ResourceProjects.org

**Comment by anjesh** [comment] 2015-07-27 11:52
linked to https://github.com/NRGI/resourcecontracts.org/issues/142

**Comment by anjesh** [comment] 2015-08-10 13:08
Moving to sprint 6, need list for this.

**Comment by anderspeders** [comment] 2015-08-12 15:59
Postponing this for now.

**Comment by anjesh** [comment] 2015-08-31 07:34
Need to pull the corporate group from opencorporates using auto-suggest.
e.g. https://opencorporates.com/corporate_groupings/tullow+oil

**Comment by anjesh** [comment] 2015-08-31 07:34
linked to #142

**Comment by anjesh** [comment] 2015-08-31 07:37
duplicate of https://github.com/NRGI/resourcecontracts.org/issues/179
closing this issue.

**Closed by anjesh** 2015-08-31 07:37 UTC
Labels: 0 - Backlog, duplicate, enhancement / blue sky wish list, Metadata
