### ISSUE TITLE
Re-adding space for legislation links on meta-data column

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#894] opened 2016-05-20 13:10 UTC
We seem to have lost the AMLA links on RC; I'm not sure what the reason for this was?

Some contracts still have the link on the metadata/summary page. Eg: http://www.resourcecontracts.org/contract/ocds-591adf-CM3558525264RC

But I can't see where to add it now on the back-end.

Here’s what it used to look like on the right hand column: https://github.com/NRGI/resourcecontracts.org/issues/397

No threads on github seem to discuss deleting it from RC: https://github.com/NRGI/resourcecontracts.org/issues?q=is%3Aissue+legislation+is%3Aclosed
1. Would it be possible to contemplate bringing the legislation links back to the right column (only where there is an entry)?
2. OLC may also be interested in this in the future. We would like to have the feature hidden for now but the ability to unhid later on if a reliable legislation source is identified.

**Comment by manishgs** [comment] 2016-05-24 10:49
Currently we are showing legislation link on RC site only and link is hidden on contracts having Hydrocarbons, Oil or Gas resource.

Let us know if we need to update restriction logic to hide the link ? @SamCCSI

**Comment by SamCCSI** [comment] 2016-05-24 12:32
Thanks @manishgs . We should keep hiding the AMLA / legislation link for hydrocarbons, etc, because AMLA only provides legislation for mining contracts.

But more generally:
1. CCSI has a preference to have the AMLA link (when visible) display on the right hand metadata column.
2. We also just want to keep open the option of having legislation sources for (i) OLC and (ii) potentially hydrocarbons, etc. contracts on RC.

cc @anderspeders @KaitlinCCSI @jedm

**Comment by manishgs** [comment] 2016-06-28 05:07
@SamCCSI  @anderspeders  @KaitlinCCSI  @jedm 
Let us know if we are ready to implement.

**Comment by SamCCSI** [comment] 2016-06-28 12:26
@manishgs yes ready, thanks.

To confirm: OLC will not have AMLA links, but we want the possibility of having a link to legislation from a different site.

**Comment by upasna01** [comment] 2016-07-01 12:41
The issue is fixed, please do verify.

http://www.resourcecontracts.org/contract/ocds-591adf-CD1072178188RC/view

![894](https://cloud.githubusercontent.com/assets/11477899/16521833/50f33fe6-3fb9-11e6-893b-7dedfe002249.png)

**Comment by SamCCSI** [comment] 2016-07-01 13:43
@upasna01 I don't see where I add the legislation link on the back end
http://resourcecontracts.elasticbeanstalk.com/contract/create

Has it been hidden?

**Comment by KaitlinCCSI** [comment] 2016-07-01 14:18
Also I think there should be a space between country name and legislation, OR legislation should be at the very bottom of the column (which is where Jed had originally put it in mockup, and which is my preference). @jedm what do you think?

**Comment by jedm** [comment] 2016-07-01 20:00
Legislation must be at bottom as spec-ed. Thanks, @KaitlinCCSI!

**Comment by hello-deepak** [comment] 2016-07-04 10:47
Fixed. 
![legislation](https://cloud.githubusercontent.com/assets/7577697/16558344/ce786412-4204-11e6-882a-162b3ac78d3e.png)

**Comment by SamCCSI** [comment] 2016-12-20 16:27
Reopening to account for possibility of OLC legislation links in the future.

**Comment by charlesyoung** [comment] 2020-10-27 12:48
@SamCCSI can I close this ticket?

**Comment by charlesyoung** [comment] 2021-06-01 10:56
@SamCCSI can I close this ticket?

**Closed** 2021-06-01 12:55 UTC
Labels: On Hold
