### ISSUE TITLE
Add normal address field to contract area location. Field name: deliveryAddress

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#484] opened 2015-10-06 22:36 UTC
For contracts which does not have a detailed contract area defined by lat, long it is recommended that a basic address is provided. 

Suggested field name to ensure compliance with OPCD: _deliveryAddress_

**Comment by charlesyoung** [comment] 2015-10-08 12:08
Should we not rather add project location reference information (case #488) to contacts with no coords than a basic address?

**Comment by jpmckinney** [comment] 2015-12-14 18:06
[Note, the #488 referenced above was marked duplicate of #447.]

See [this comment](https://github.com/NRGI/resourcecontracts.org/issues/447#issuecomment-164508893) about why `deliveryAddress` is the incorrect semantics, so the property should be named differently, possibly `productionAddress`.

Do we expect the contract location to differ from the project location? Can you give an example?

**Comment by jpmckinney** [comment] 2015-12-14 18:07
@charlesyoung Assigning a lat/lng suggests a greater precision than assigning some high-level address descriptors (e.g. region). So, I think there's value in being able to provide either/both.

**Comment by jpmckinney** [comment] 2015-12-15 19:00
Note that there's agreement in the OC issue that `deliveryAddress` is incoherent for extractives: https://github.com/open-contracting/standard/issues/250#issuecomment-146414233

**Comment by charlesyoung** [comment] 2016-12-07 06:27
@anderspeders is this still required?

**Comment by charlesyoung** [comment] 2017-01-20 06:29
Linked to 'Add geo-data metadata in the Admin interface' #942

**Closed by charlesyoung** 2017-01-20 06:29 UTC
Labels: 0 - Backlog, Metadata
