### ISSUE TITLE
Document DB table or collection

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#13] opened 2015-05-29 16:06 UTC
Metadata and indexing should be available in db collection or table and via API. This can be PostGres or Mongo but Mongo would allow us to implement something like JSON-LD relatively easily and sidestep linked data issues and complexity.

**Comment by anjesh** [comment] 2015-06-03 11:11
We are using PostGres json datatype for contracts metadata. This could be closed, possible duplicate of See #24.

**Closed** 2015-06-16 13:13 UTC
Labels: duplicate
