### ISSUE TITLE
commenting on metadata

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#165] opened 2015-07-31 21:06 UTC
As a reviewer, i need to comment on individual metadata categories.

I also need to be able to do this without clicking "complete" on metadata, which right now seems to be the only way to add comments.

(No worries if this is already in the pipeline - I'm just relaying feedback from reviewing real metadata entries)

**Comment by anderspeders** [comment] 2015-08-05 00:15
Thanks Sam, 

We have added some commenting to the pipeline, so I hope to have something to share there relatively soon.

**Comment by anjesh** [comment] 2015-08-10 13:25
Duplicate of #146 
Further discussion there.

**Closed by anjesh** 2015-08-10 13:25 UTC
Labels: duplicate, feature request, Metadata
