### ISSUE TITLE
Showing the article reference from each contract

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#72] opened 2015-06-16 15:19 UTC
As a user I need to see the source(s) of the information contained in a plain text annotation. In the old version of the website, this is done by including "-- Arts. 5.2, 6.5" after the annotation. See below.

![image](https://cloud.githubusercontent.com/assets/12913915/8186627/5224325c-1419-11e5-80d7-f65f15c978c8.png)

This will be important even if the annotation links to the particular text - the user should be able to immediately see the source(s) of information without having to physically navigate the contract.

**Comment by SamCCSI** [comment] 2015-07-08 12:53
Just checking in on this issue

**Comment by anjesh** [comment] 2015-07-13 04:54
Is that something that is done by the researcher? Is there any sort of change in the existing annotation process to capture the info you have suggested?
cc @anderspeders

**Comment by SamCCSI** [comment] 2015-07-13 12:28
Right now the researcher makes the annotation, and then notes which article references the information in the annotation comes from. See below - note how it says "Arts. 1.2 and 3.1" 
![image](https://cloud.githubusercontent.com/assets/12913915/8649530/2d89170c-2939-11e5-97ea-96b745ef309d.png)

**Comment by anjesh** [comment] 2015-07-13 12:32
Is that something annotator writes during annotation or the system automatically finds in the document based on the selection?

**Comment by SamCCSI** [comment] 2015-07-13 12:37
The annotator writes it during the annotation.

On Mon, Jul 13, 2015 at 8:32 AM, Anjesh <notifications@github.com> wrote:

> Is that something annotator writes during annotation or the system
> automatically finds in the document based on the selection?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/72#issuecomment-120911132>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment] 2015-07-13 12:51
That means there doesn't need to make any changes in the system, the existing annotation interface does it. The annotator just has to write that at the end of the annotation text. Is that right?

**Comment by anjesh** [comment] 2015-07-27 08:51
Not clear if this is sorted, now we can add tag and categories separately. The article or similar info could be part of the tags now.

**Comment by anjesh** [comment] 2015-07-27 11:23
Moving to sprint5, just in case.

**Comment by SamCCSI** [comment] 2015-07-27 13:34
Thanks Anjesh. I would appreciate clarification from Anders or Chris on
this in due course.

On Mon, Jul 27, 2015 at 7:23 AM, Anjesh <notifications@github.com> wrote:

> Moving to sprint5, just in case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/72#issuecomment-125171822>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anderspeders** [comment] 2015-08-08 22:00
@SamCCSI Let's discuss this again on Monday.

**Comment by jedm** [comment] 2015-09-25 16:31
Also requested in PDFs sent 7 September and 18 September. See #373

**Comment by anjesh** [comment] 2015-09-30 11:08
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/391

**Closed by anjesh** 2015-09-30 11:08 UTC
Labels: 0 - Backlog
