### ISSUE TITLE
Make PDF-view the default for the contract page

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#239] opened 2015-09-02 16:25 UTC
![make pdf-view the default](https://cloud.githubusercontent.com/assets/1101585/9637235/a21f05e8-516d-11e5-88b6-94cde350d909.JPG)

**Comment by anjesh** [comment] 2015-09-09 07:13
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/238

**Closed by anjesh** 2015-09-09 07:13 UTC
Labels: Front end / UI - general category, UI - Contract page
