### ISSUE TITLE
Fixing & Streamlining All Search pages

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#895] opened 2016-05-20 19:09 UTC
**For results page of Search on no text OR if user clicks “Advanced Search” from Homepage:**
1. Change page title (for these 2 cases ONLY) to “**All Documents**”
2. Hide existing search box
3. Add global search to top bar (like “Countries,” “Resources” pages)
_see image below_

**If user submits a new text search from any global search box:**
1. Add global search box to top bar (like “Countries,” “Resources” pages)
2. Change text in existing search box to “**Change or refine your search**”
3. Change magnifying glass color to dark gray (like “Countries,” “Resources” pages)
_see image below_

**When user clicks “View by Country” from burger menu or Homepage:**
1. Remove breadcrumb
2. Change text in search box to “Enter Country name or select Country below”
3. Change “Filter by Resource” on right side:
- Remove current filter function
- Change text to “**View by Resource**”
- Remove icon
- Click takes user to “Resources” page (…/resources)<br>
 _see image below_

**When user clicks “View by Resource” from burger menu or Homepage:**
1. Remove breadcrumb
2. Change text in search box to “Enter Resource name or select Resource below”
3. Change “Filter by Country” on right side:
- Remove current filter function
- Change text to “**View by Country**”
- Remove icon
- Click takes user to “Countries” page (…/countries)<br>
_see image below_

**For _ALL SEARCH PAGES_, make the following changes wherever relevant:**
1. In circle with results total, change “CONTRACTS” to “DOCUMENTS”
2. Add Back button (also on “Countries” and “Resources” pages)
3. Change “Annotations Category” to “**Annotation Category**” - per request from [seven months ago](https://github.com/NRGI/resourcecontracts.org/issues/493#issuecomment-146489996)
4. Add Annotations-only checkbox - per #891 
5. Update sharing and download buttons per #890 
_see image below_

![slide05](https://cloud.githubusercontent.com/assets/2153664/15438903/3f34e0b8-1e83-11e6-84c3-7ffd83228a00.jpg)
![slide06](https://cloud.githubusercontent.com/assets/2153664/15438905/3f38514e-1e83-11e6-95a6-3f6ea84a650f.jpg)
![slide07](https://cloud.githubusercontent.com/assets/2153664/15438906/3f38a05e-1e83-11e6-8816-835ebe326832.jpg)
![slide08](https://cloud.githubusercontent.com/assets/2153664/15438908/3f3ff25a-1e83-11e6-8c04-b0f46c8b1204.jpg)
![slide09](https://cloud.githubusercontent.com/assets/2153664/15438904/3f3632d8-1e83-11e6-8d7e-ae37773a8140.jpg)
![slide10](https://cloud.githubusercontent.com/assets/2153664/15438907/3f3965ca-1e83-11e6-8ee5-08ee903dd4cf.jpg)

**Comment by hello-deepak** [comment] 2016-05-27 08:42
@jedm Please clarify.

> RC/OLC Simplify search pages (Text Search page)
![search](https://cloud.githubusercontent.com/assets/7577697/15602553/a6a97488-2415-11e6-8ca0-7422f7c24dee.png)
1. Global search (Same as "Countries" "Resource" pages)
2. Filter for search .

* Does search page is going to have two drop down of filter ? One from global search and another from filter below .

**Comment by jedm** [comment] 2016-05-27 13:54
Dear Deepak,

To make sure I answer your question properly, can you please confirm which of the 5 requests above you are referring to, and also please rephrase your question text?

Thanks very much for helping me to understand. 

Jed

**Comment by hello-deepak** [comment] 2016-05-31 06:21
I am referring to 
> For results page of Search on no text OR if user clicks “Advanced Search” from Homepage (first request ) .
  *  Add global search to top bar (like “Countries,” “Resources” pages)  (no. 3)

If we add "Global search" in top bar then this search [page](http://www.resourcecontracts.org/search) is going to have two filter option for search. one from global search and other from filter option in search page (which is highlighted in earlier comment image).

**Comment by jedm** [comment] 2016-05-31 06:32
Thanks for clarifying, @hello-deepak! Actually, there will not be two search options in this scenario because, per the very next bullet in the first request [(#1 of 5)](https://github.com/NRGI/resourcecontracts.org/issues/895#issue-156031201), you should **hide the existing search box** from this screen.

![slide05a](https://cloud.githubusercontent.com/assets/2153664/15665216/80b8787c-26be-11e6-91fe-0c97dc7f30c1.jpg)

Happy to clarify further if useful.

**Comment by upasna01** [comment] 2016-06-16 11:56
The issue is fixed now please do verify.

http://rc-site-demo.elasticbeanstalk.com/rc/public/search?q=
![895](https://cloud.githubusercontent.com/assets/11477899/16115894/807b8420-33e9-11e6-894b-18456c636157.png)

**Comment by jedm** [comment] 2016-06-19 02:15
About 6 of the 15 requested changes have not been made (in bold below) - please fix:

For results page of Search on no text OR if user clicks “Advanced Search” from Homepage:
1. Change page title (for these 2 cases ONLY) to “All Documents”
2. Hide existing search box
**3. Add global search to top bar (like “Countries,” “Resources” pages) - per mockup provided, this should be TOP bar (to the right of the logo), as it is in the pages referenced. Should NOT create an extra row as it does now**

If user submits a new text search from any global search box:
**1. Add global search box to top bar (like “Countries,” “Resources” pages) - see above**
**2. Change text in existing search box to “Change or refine your search” (cannot tell if this is done since demo site is in French)**
**> NEW fix: French text length and font size block display of full message**
**3. Change magnifying glass color to dark gray (like “Countries,” “Resources” pages)**

When user clicks “View by Country” from burger menu or Homepage:
1. Remove breadcrumb
2. Change text in search box to “Enter Country name or select Country below” **French text length and font size block display of full message**
3. Change “Filter by Resource” on right side:

When user clicks “View by Resource” from burger menu or Homepage:
1. Remove breadcrumb
2. Change text in search box to “Enter Resource name or select Resource below” **French text length and font size block display of full message**
3. Change “Filter by Country” on right side:

For ALL SEARCH PAGES, make the following changes wherever relevant:
1. In circle with results total, change “CONTRACTS” to “DOCUMENTS”
**2. Add Back button (also on “Countries” and “Resources” pages)****
**> Back Button is wrong height. Fix so it fits in the row. (See image attached below)**
**3. Change “Annotations Category” to “Annotation Category” - per request from seven months ago (cannot tell if this is fixed in English version**
**4. Add Annotations-only checkbox - per #891**
**5. Update sharing and download buttons per #890** 

**> NEW: Bad UI for the Advanced Search tool to appear on click. Suggest we remove Advanced Search when entering a "first search" unless user has clicked "Advanced Search from homepage** 

![screen shot 2016-06-18 at 6 59 02 pm](https://cloud.githubusercontent.com/assets/2153664/16174795/0205edb4-3589-11e6-95b3-7e65b4d5e559.png)

**Comment by hello-deepak** [comment] 2016-06-27 11:30
Please review this issue [here](http://www.resourcecontracts.org/)

**Comment by jedm** [comment] 2016-06-30 04:21
Four last fixes. 3 were requested at beginning of thread and not yet made. One is new.

If user submits a new text search from any global search box:
> 1. Add global search box to top bar (like “Countries,” “Resources” pages) - see above
**Search box in top bar should say "Search all documents" - not text string searched**
> 2. Change text in existing search box to “Change or refine your search”
**This change has not been made yet**
> 3. Change magnifying glass color to dark gray (like “Countries,” “Resources” pages)
**Please change magnifying glass icon in _lower_ box ("Change or refine...") back to LIGHT gray. (Apologies for reversal. This is for consistency with other pages.)**

> Bad UI for the Advanced Search tool to appear on click. Suggest we remove Advanced Search when entering a "first search" unless user has clicked "Advanced Search" from homepage
**This change has not been made. Strongly suggest making it because the automatic Advanced Search popup will confuse people. Should appear for RESULTS not for blank box in top (Search all documents) bar.** @anderspeders @KaitlinCCSI @charlesyoung what do you think?

**Comment by KaitlinCCSI** [comment] 2016-06-30 13:52
Re last question about advanced search page. I think that's fine to not have it appear on clicking into text search bar BUT is there any way to easily access it for people without having to first do a text search? For example, could there be the text search area and then next to it a smaller hyperlinked "Advanced Search" line or something, and when that line is clicked the advanced search tool appears? Otherwise it just seems that if the user misses the advanced search option on home page it will be hard for them to find this tool, which is an important one for the site?

**Comment by jedm** [comment] 2016-06-30 21:46
I do not think it is necessary to have the Advanced Search option before your first results display, but I am happy to be outvoted by @anderspeders or @charlesyoung or @byndcivilization.

**Comment by hello-deepak** [comment] 2016-07-01 08:21
@jedm 
> Change text in existing search box to “Change or refine your search”

 "Change or refine your search" is placeholder of input field, which disappear when search text string appears.
![1](https://cloud.githubusercontent.com/assets/7577697/16515644/e4df7840-3f92-11e6-98c4-5f69fe2b8186.png)

![2](https://cloud.githubusercontent.com/assets/7577697/16515646/e7201aa6-3f92-11e6-96f5-97d15a83e657.png)

We can remove text string from that appears in input field in order to show "Change or refine your search".

Feedback please.

**Comment by jedm** [comment] 2016-07-01 13:06
The repetition of the term that is searched (eg, "environment") is redundant, and confusing for the user. That is why this request was made. 

You raise a good point, however, that if user wants to "refine" it might be better to have the original term pre-populated. 

Would welcome a suggestion or preference from @byndcivilization.

**Comment by KaitlinCCSI** [comment] 2016-07-01 14:45
Jed re whether Advanced Search should be an option without having to first search in text field -- I see this as very useful aspect of the site, so if there is a way to have it available, I would have a strong preference for that.

**Comment by jedm** [comment] 2016-07-01 20:03
Would welcome a suggestion or preference from @byndcivilization.

**Comment by jedm** [comment] 2016-07-08 17:27
Would welcome a suggestion or preference from @byndcivilization.

**Comment by jedm** [comment] 2016-08-10 21:39
Dear @anjesh and @rprajapatii ,

The many design improvements to the Search pages and Social buttons are **beautiful.** Thank you.

We still owe you an answer for the question above about how Advanced Search appears.

Another request from May still needs to be address, regarding the presence of a duplicate search box in some conditions. Please see this comment: https://github.com/NRGI/resourcecontracts.org/issues/895#issuecomment-222603231 Thank you!

Jed

**Comment by hello-deepak** [comment] 2016-09-27 10:52
I think this can be closed . #973 covers the question on "how advanced search appears?" .

Please use #973 for further discussion .

**Closed by hello-deepak** 2016-09-27 10:52 UTC
Labels: 2 - Working, Front end / UI - general category, Priority, UI - Advanced search view
