### ISSUE TITLE
Search page > Contract Type and Annotations Category dropdowns 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#465] opened 2015-10-05 17:39 UTC
Hi @anderspeders @anjesh - I can't click on the Contract Type or Annotations Category dropdown menus when using Chrome on a PC (not having this issue using Chrome on a Mac). 

cc @KaitlinCCSI

**Comment by anderspeders** [comment] 2015-10-05 17:58
I am accessing this fine via chrome. For example I've browsed through both dropdowns to reach this search result: 
http://alpha.openlandcontracts.org/search?q=&contract_type%5B%5D=Contrat+de+Concession+Foresti%C3%A8re&annotation_category%5B%5D=Arbitration+and+dispute+resolution%2F%2FArbitrage+et+r%C3%A8glement+des+diff%C3%A9rends

Can you provide screen shot?

**Comment by KaitlinCCSI** [comment] 2015-10-05 18:02
Just a note that I also had this happen to me last week (and had logged a
ticket), but then it appeared to resolve itself on its own. So seems like
there might be some kind of bug here.

On Mon, Oct 5, 2015 at 12:58 PM, Anders <notifications@github.com> wrote:

> I am accessing this fine via chrome. For example I've browsed through both
> dropdowns to reach this search result:
>
> http://alpha.openlandcontracts.org/search?q=&contract_type%5B%5D=Contrat+de+Concession+Foresti%C3%A8re&annotation_category%5B%5D=Arbitration+and+dispute+resolution%2F%2FArbitrage+et+r%C3%A8glement+des+diff%C3%A9rends
>
> Can you provide screen shot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/465#issuecomment-145614670>
> .
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PptWD5J&m=569134751bce&t=20151005&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01PptWD5J&m=569134751bce&t=20151005&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01PptWD5J&m=569134751bce&t=20151005&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by JesseCCSI** [comment] 2015-10-05 18:04
Hi @anderspeders - unfortunately the issue doesn't show up well on screenshots (the mouse icon disappears when I screenshot), but this is the issue... 
- Nothing happens when I try to click on the Annotations Category or Contract Type dropdown (mouse icon remains an arrow) 
- Whereas when I move my mouse to other dropdowns, the arrow changes to a cursor and allows me to either type or select a menu item 
![image](https://cloud.githubusercontent.com/assets/14910764/10288918/a863f682-6b69-11e5-8a90-8e1d54efeb42.png)

**Comment by anderspeders** [comment] 2015-10-05 18:08
Thanks @JesseCCSI, 

@anjesh: Any suggestions for fixes here?

**Comment by anjesh** [comment] 2015-10-06 02:48
Not sure when the problem is random. It's fine in the mac and linux chrome, firefox and safari here. Haven't checked in PC though. Will do and see if we could replicate the same.

**Comment by anjesh** [comment] 2015-10-06 03:27
@sweetanzell can you see if you can replicate this in the PC chrome?

**Comment by anjesh** [comment] 2015-10-06 11:00
Yes we found the problem, it was due to some CSS thing when the browser size is reduced. Fixed now.

**Closed by anjesh** 2015-10-06 11:00 UTC
Labels: bug, Priority, UI - Advanced search view
