### ISSUE TITLE
English - French translation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#503] opened 2015-10-08 13:54 UTC
Working document: 
https://docs.google.com/spreadsheets/d/1GjnhV9fLFl_-9EHyQdpPO9X7yYysIJJkAhakWXEnOT0/edit#gid=0

1) YI will prepare list of string text that needs translation
2) Anders will follow up with @samCCSI @KaitlinCCSI on translation to French
3) YI will implement

**Comment by anderspeders** [comment] 2016-02-08 22:48
Postponing this for now - based on prioritization.

**Comment by anjesh** [comment] 2016-05-23 09:14
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/47#issuecomment-196803183

**Closed by anjesh** 2016-05-23 09:14 UTC
Labels: 2 - Working, Priority
