### ISSUE TITLE
Contract View - Clean Up Toolbar

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#900] opened 2016-05-31 04:48 UTC
To reduce clutter and conserve space in Contract View toolbar:

- Delete word "Zoom" and replace with icon (see example below *)
- New icon must be same height and color match for TEXT and PDF icons
- Move zoom tool to the left
- Resize - / + zoom buttons to same height as the white box that has the current page number (or reduce size of page number box)
- Reduce font size of page number tool to same font size as the words "TEXT" and "PDF"
- Make sure zoom tool, page number tool, Text/PDF toggle and sharing buttons to the right are MIDDLE-ALIGNED

![slide1](https://cloud.githubusercontent.com/assets/2153664/15664011/3e59bb70-26b5-11e6-978c-2dac81d4bd48.jpg)
![toolbar_alignment](https://cloud.githubusercontent.com/assets/2153664/15663433/eff8ae14-26af-11e6-887f-0fb7e77588f4.jpg)
![toolbar_font_height](https://cloud.githubusercontent.com/assets/2153664/15663434/effdea3c-26af-11e6-8f66-6b41dda3088f.jpg)

**Comment by upasna01** [comment] 2016-06-16 11:31
The issue is fixed now, please do verify.
![900](https://cloud.githubusercontent.com/assets/11477899/16115333/12dc8d0e-33e6-11e6-9ae1-4f7327bdef66.png)


http://www.resourcecontracts.org/contract/ocds-591adf-PE0065433224RC/view#/pdf

**Comment by jedm** [comment] 2016-06-17 23:56
Looks very nice. A few last fixes:

- New Zoom icon should be a few pixels lower and a few pixels to the right, in order to match other doc icons and be centered between -/+ signs

- Box containing minus sign is a few pixels smaller than box containing plus sign - please fix

- As noted in https://github.com/NRGI/resourcecontracts.org/issues/889#issuecomment-226550865 on Social Sharing, move download, social tools to the right and separate from PDF/view tools the same way Annotation tools have a separator in the left column

**Comment by hello-deepak** [comment] 2016-06-27 11:14
@jedm 
Since the zoom icon as you have mentioned was not clearly visible in contract view page ,  we have changed the icon .
Please review this issue [here](http://www.openlandcontracts.org/contract/ocds-591adf-SS5768196941OL/view) .

**Comment by upasna01** [comment] 2016-06-30 05:33
The issue on zoom icon and social sharing button is fixed, I think this issue is safe to close for now.  
Please do verify [here](http://www.resourcecontracts.org/contract/ocds-591adf-SL0498783225RC-1832/view)

**Closed by upasna01** 2016-06-30 05:33 UTC
Labels: Front end / UI - general category, UI - Contract page
