### ISSUE TITLE
Country-specific front-end ("subsite")

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#46] opened 2015-06-13 16:03 UTC
As a government official in a country (in a ministry or an EITI MSG, for instance), I want to have my country's contracts available using the RC framework so that I can provide a new degree of contract transparency even if there are limitations to the IT capacity of my agency or MSG. 

Like the contracts review committee in Guinea, I need the ability to brand the repository with national features on the front end, such as visual identity and even a lightweight blog for content pages specific to my work.

**Comment by anjesh** [comment] 2015-08-31 08:34
duplicate of https://github.com/NRGI/resourcecontracts.org/issues/177

**Closed by anjesh** 2015-08-31 08:34 UTC
Labels: Front end / UI, User story
