### ISSUE TITLE
Create annotation workflow

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#34] opened 2015-06-10 13:45 UTC
As an administrator I wish to ensure that an annotator (eg graduate student) will be going through all 20 steps of the annotation process (each step being a tag that must be identified in the contract and summarized in text).

**Comment by anjesh** [comment] 2015-06-15 09:05
can we differentiate "tag" as free-text field and bring in "category" which consists to list of options once this list from #32 is finalized. annotatorjs has categories functionality, still needs to be researched. currently one of the pre-filled strings are auto-suggested during tagging in annotation.

**Comment by anjesh** [comment] 2015-07-09 10:34
Duplicate of #112

**Closed by anjesh** 2015-07-09 10:34 UTC
Labels: annotations, duplicate, User story
