### ISSUE TITLE
RC Admin Module: Multilingual look-up tables

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#628] opened 2015-11-04 06:42 UTC
The admin look-ups contain a combination of French and English values as noted below. This method is messy and isn't sustainable because we will probably need to include Spanish and Portuguese values in the not too distant future. Can we not filter the relevant look-ups based on the selected language? 

![image](https://cloud.githubusercontent.com/assets/13888372/10931294/ddcbe77c-82ce-11e5-9c51-18081167b65d.png)

**Comment by anderspeders** [comment] 2015-11-12 12:59
Agree. We will need a proper translation of the site in order to address this.

**Comment by anjesh** [comment] 2016-01-15 11:04
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/47
Further discussion there.

**Closed by anjesh** 2016-01-15 11:04 UTC
Labels: feature request
