### ISSUE TITLE
MT not letting us reject pages that were submitted but weren't transcribed

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#550] opened 2015-10-19 12:55 UTC
![screen shot 2015-10-19 at 8 55 02 am](https://cloud.githubusercontent.com/assets/12913915/10578277/27782166-763f-11e5-96d5-51739ef84eab.png)

**Comment by SamCCSI** [comment] 2015-10-19 13:03
Also, We have altered the PDF document to make it more readable / OCR processable. I assume it's ok to "change" the PDF to the new file, even with these MT pages pending? (OCR didn't work for the original file)

**Comment by anderspeders** [comment] 2015-10-19 15:13
Just to clarify, what does alter mean? Have you uploaded a new document?

(I was not even aware that this was possible).

**Comment by SamCCSI** [comment] 2015-10-19 21:19
Yes it's possible to replace the PDF. YI built in this feature recently.

@anjesh you are probably best placed to answer my query above? Thanks!

**Comment by anjesh** [comment] 2015-10-20 01:30
Yes the pdf could be replaced now as per this https://github.com/NRGI/resourcecontracts.org/issues/427#issuecomment-148681170

And it removes the existing pages (both pdf and text) and replaces them with the pages/text of the new pdf. Annotations and metadata remains as they are.

**Comment by SamCCSI** [comment] 2015-10-20 12:38
Thanks Anjesh.

**Comment by anjesh** [comment] 2015-11-16 09:12
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/626

**Closed by anjesh** 2015-11-16 09:12 UTC
Labels: 1 - Ready, bug, Mechanical Turk workflow
