### ISSUE TITLE
Invalid Signature Date

### ISSUE THREAD

**Issue by hello-deepak** [NRGI/resourcecontracts.org#867] opened 2016-04-28 10:23 UTC
These contracts have "00" in day/month field of signature date.

http://admin.resourcecontracts.org/contract/1355
http://admin.resourcecontracts.org/contract/938
http://admin.resourcecontracts.org/contract/897
http://admin.resourcecontracts.org/contract/139
http://admin.resourcecontracts.org/contract/987

Please update with valid date and publish it.

cc @anderspeders @charlesyoung @SamCCSI

**Comment by SamCCSI** [comment] 2016-04-28 12:55
I believe these documents are undated, which is why their date is 00.

We would prefer to leave them like that than to create false metadata.

Anders, any thoughts? These contracts were updated by Dave as part of his
retrofitting of metadata.





*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School | The Earth Institute, Columbia University
435 W116th St. New York, NY 10027
| (+1)(212) 854-2635 <+1212-854-2635> | (+1)(646) 630-4123 <+1646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

*New Report: Land Deal Dilemmas: Grievances, Human Rights, and Investor
Protections
<http://ccsi.columbia.edu/2016/03/10/land-deal-dilemmas-grievances-human-rights-and-investor-protections/>*
Available at: *http://goo.gl/qctX9I <http://goo.gl/qctX9I>*

**Comment by anderspeders** [comment] 2016-05-04 13:24
As I understand these do have at least signature year - so if we ensure that the "signature year" field is complete we can remove the "signature date" completely. 

I just did this for one of the contracts.

**Comment by SamCCSI** [comment] 2016-05-04 13:37
@anderspeders What year did you use?

**Comment by upasna01** [comment] 2016-05-31 05:29
@anderspeders does it mean the signature date is to be completely removed from metadata.
As for the signature year it is already mandatory.

**Comment by upasna01** [comment] 2016-06-07 04:19
Please confirm the changes @anderspeders

**Comment by upasna01** [comment] 2016-06-13 05:44
I thin the issue is safe to close for now.

**Comment by SamCCSI** [comment] 2016-06-13 12:00
Reopening. @anderspeders could you let us know what year to enter when there is no indication of the signature date?

**Comment by upasna01** [comment] 2016-06-14 09:12
@SamCCSI In case of no indication of the signature date, signature date can be left blank, only signature year is a mandatory field as shown below:
![date](https://cloud.githubusercontent.com/assets/11477899/16037450/426b5e30-3240-11e6-938f-d1e54cea9b8a.png)

**Comment by SamCCSI** [comment] 2016-06-14 12:05
If we don't know the year, what year should we include as metadata?

On Jun 14, 2016, at 5:13 AM, upasna01 <notifications@github.com> wrote:

@SamCCSI <https://github.com/SamCCSI> In case of no indication of the
signature date, signature date can be left blank, only signature year is a
mandatory field as shown below:
[image: date]
<https://cloud.githubusercontent.com/assets/11477899/16037450/426b5e30-3240-11e6-938f-d1e54cea9b8a.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NRGI/resourcecontracts.org/issues/867#issuecomment-225824113>,
or mute the thread
<https://github.com/notifications/unsubscribe/AMUM-_MsffFIfYD-2sMUOVoS8bVdhj9oks5qLnCZgaJpZM4IRyGg>
.

**Comment by upasna01** [comment] 2016-06-15 03:54
I think we will need @anderspeders opinion on this one.

**Comment by manishgs** [comment] 2016-07-05 07:33
Closing for now.

**Comment by SamCCSI** [comment] 2016-07-05 12:55
Re-opening. @anderspeders what do you think is the answer to my query above?

**Comment by charlesyoung** [comment] 2016-12-07 06:39
@anderspeders is this still required?

**Closed** 2017-01-17 14:43 UTC
Labels: Needs discussion, question
