### ISSUE TITLE
Word File Download 

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#912] opened 2016-06-15 19:23 UTC
Two issues. 

1. The Word Download is now for some reason named Global_Word_File. 
2. I get a '404! The page you’re looking for doesn't exist' error when clicking on the Global_Word_File because the PDF text hasn't yet been published so it shouldn't and isn't available for download. 

![image](https://cloud.githubusercontent.com/assets/13888372/16094095/e02dffa2-333e-11e6-888c-a85ca7e4a828.png)

**Comment by upasna01** [comment] 2016-06-16 11:28
The issue is fixed now, please do verify.

![word-file](https://cloud.githubusercontent.com/assets/11477899/16115227/76fb1f04-33e5-11e6-81fe-c0dd0028dfe9.png)

http://www.resourcecontracts.org/contract/ocds-591adf-PH6493643447RC

**Closed by upasna01** 2016-06-16 11:28 UTC
Labels: bug
