### ISSUE TITLE
Titles of contracts

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#172] opened 2015-08-04 18:59 UTC
Would it be possible to have a detailed description (including the project's location, signature date, etc) listed next to the title of each contract? This way, contract names would stay concise and clear, but users could still distinguish between multiple contracts that have the same country, company, year and type of contract.

To clarify: we were thinking that the site could list the names of the contracts, and then right under the names, where you currently see the info on when last updated and the annotation links, you could include information about the block/region/location and date of signature. That way anyone using the site could see ALL of this info right away, but it keeps the names cleaner and easier to read. To do this, we would need to build the site to allow this type of description right under the name, which we currently can't do.

**Comment by anderspeders** [comment] 2015-08-04 19:26
Thanks Sam, Just to clarify that this refers to the front end?

**Comment by SamCCSI** [comment] 2015-08-04 19:28
That's correct - front end, so the focus is users (rather than CCSI/WB
staff).

Thanks Anders.

On Tue, Aug 4, 2015 at 3:26 PM, Anders <notifications@github.com> wrote:

> Thanks Sam, Just to clarify that this refers to the front end?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/172#issuecomment-127728431>
> .
>



-- 



*SAM SZOKE-BURKE*
*Legal Researcher**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| (212) 854-2635 <212-854-2635> | (646) 630-4123 <646-630-4123>
| s.burke@columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @samszokeburke <http://twitter.com/samszokeburke>

**Comment by anjesh** [comment] 2015-09-07 08:36
duplicate of https://github.com/NRGI/resourcecontracts.org/issues/230

**Closed by anjesh** 2015-09-07 08:36 UTC
Labels: 1 - Ready, Front end / UI - general category
