### ISSUE TITLE
External notifications

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#846] opened 2016-03-31 11:54 UTC
I've been asked a couple of times if RC allows for notifications based on users selection criteria. As an example; send me an email when new contracts or supporting documents are published for the DRC. 

Not a priority so labeled as blue sky.

**Comment by anjesh** [comment] 2016-05-24 04:53
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/126

**Closed by anjesh** 2016-05-24 04:53 UTC
Labels: enhancement / blue sky wish list, question
