### ISSUE TITLE
Link to work download option broken

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#920] opened 2016-06-24 14:05 UTC
Here's an example: 
http://www.resourcecontracts.org/contract/ocds-591adf-AZ3743790345RC/download/word

![image](https://cloud.githubusercontent.com/assets/1101585/16339898/2612d032-39f3-11e6-9737-d1e5ad241301.png)

**Comment by upasna01** [comment] 2016-06-27 08:48
The issue is fixed now. The download is working, please do verify.

**Closed by upasna01** 2016-06-27 08:48 UTC
Labels: bug
