### ISSUE TITLE
Change <Document type> to mandatory, change <Contract type> to non-mandatory

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#776] opened 2016-02-07 02:44 UTC
As per contract tally proposal from @KaitlinCCSI @SamCCSI.

**Comment by anjesh** [comment] 2016-02-07 09:29
These two codelist related issues should also be addressed along with this issue https://github.com/NRGI/resourcecontracts.org/issues/721 and https://github.com/NRGI/resourcecontracts.org/issues/720

Here's the codelists for [contract-type](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=0) and [document-type](https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit?ts=566690b1#gid=1026386158)

**Comment by anjesh** [comment] 2016-02-07 10:05
Again duplicate of https://github.com/NRGI/resourcecontracts.org/issues/706.
It has more information on the mandatory of contract-type if the document-type is contract. Lets address this in that issue.

**Comment by SamCCSI** [comment] 2016-03-01 15:26
@anjesh thank you for making Document type mandatory.

Please make contract type non-mandatory as discussed in this ticket.

(Explanation: some document types are not contracts, hence there will be no contract type).

CC @anderspeders and @KaitlinCCSI

**Comment by KaitlinCCSI** [comment] 2016-03-01 15:28
Reopening to address Sam's comment above

**Comment by anderspeders** [comment] 2016-03-01 19:42
@anjesh @manishgs Please make <contract type> **non-mandatory** as discussed in this ticket.

**Comment by upasna01** [comment] 2016-03-02 11:46
This issue is fixed, please review the change. Here is the snapshot for it.
![contract-type](https://cloud.githubusercontent.com/assets/11477899/13459547/85e85a0a-e09c-11e5-8d8f-23d9c8a3fa1f.png)

**Closed by upasna01** 2016-03-02 11:46 UTC

**Comment by SamCCSI** [comment] 2016-03-02 15:48
Thanks @upasna01 this seems to work well.
