### ISSUE TITLE
Cluster category description - when hovering over

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#372] opened 2015-09-23 16:00 UTC
![image](https://cloud.githubusercontent.com/assets/1101585/10050481/9b801078-61ea-11e5-98d7-540035be47d9.png)

CCSI to provide summary description of each cluster category. YI to implement.

**Comment by anjesh** [comment] 2016-01-18 08:11
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/22

**Closed by anjesh** 2016-01-18 08:11 UTC
Labels: UI - Contract page
