### ISSUE TITLE
Vertical scroll for text and contract view

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/resourcecontracts.org#115] opened 2015-07-08 19:02 UTC
Pagination is usefull for record keeping but shouldn't be used for UI or rendering. PDF and raw text should both scroll.

**Comment by byndcivilization** [comment] 2015-07-08 19:03
This will be really important when we release into the wild.

**Comment by anjesh** [comment] 2015-07-09 10:29
duplicate of #84. Closing this.

**Closed by anjesh** 2015-07-09 10:29 UTC
Labels: duplicate, feature request, Front end / UI
