### ISSUE TITLE
Incorrect URL's from the google search

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#678] opened 2015-11-20 14:19 UTC
I get a '404 error' when clicking on most of below links. 

![image](https://cloud.githubusercontent.com/assets/13888372/11301821/6690437a-8fa2-11e5-974e-b12232f0984d.png)

**Comment by anjesh** [comment] 2015-11-25 08:13
It appears that the google is indexing the previous rc.org pages.

**Comment by charlesyoung** [comment] 2015-11-25 09:00
Can this be updated or redirected?

**Comment by anderspeders** [comment] 2015-12-01 22:17
I believe Google will fix this over time?

@byndcivilization

**Comment by byndcivilization** [comment] 2015-12-01 22:26
just forced it

**Comment by anjesh** [comment] 2016-01-12 09:10
Still showing some incorrect links in the google.

**Comment by anjesh** [comment] 2016-01-15 10:57
duplicate of https://github.com/NRGI/resourcecontracts.org/issues/678

**Closed by anjesh** 2016-01-15 10:57 UTC
