### ISSUE TITLE
Associating multiple phrases in single contract 

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#44] opened 2015-06-13 15:22 UTC
As an editor, I need to create links between multiple clauses of a contract under a single annotation, so that users can understand the rules created by a contract even when multiple clauses combine to define the rule.

(Best case scenario is for these linkages between clauses to exist in text layer _and_ in pdf layer)

**Comment by anjesh** [comment] 2015-06-30 08:30
Closing as this is duplicate of #71

**Closed by anjesh** 2015-06-30 08:30 UTC
Labels: duplicate, User story
