### ISSUE TITLE
<Document type> should appear before <Contract type> on the backend

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#775] opened 2016-02-07 02:32 UTC
<Document type> should appear before <Contract type> on the backend, as <Contract type> is a sub set of <Document type> (which is a broader group). 

This is to ensure clarity of process in the mind of the annotator: 
- Step 1: Select <Document Type>
- Step 2 (if applicable) select <Contract Type>

As per request of @SamCCSI in contract annotation document.

**Comment by anjesh** [comment] 2016-02-07 10:04
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/706
will be addressed in that issue.

**Closed by anjesh** 2016-02-07 10:04 UTC
