### ISSUE TITLE
Contract text view > text not appearing 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#758] opened 2016-01-13 19:28 UTC
When you click to view the text of certain contracts, the text does not appear - instead, a series of rectangles appears in place of text (see below). I've noticed this happening with a number of contracts, including the following: 

- http://www.openlandcontracts.org/contract/ocds-591adf-LR8097649233OL/view#/text 
- http://www.openlandcontracts.org/contract/ocds-591adf-ET5881570901OL/view#/text 
- http://www.openlandcontracts.org/contract/ocds-591adf-CD1670407566OL/view#/text
- http://www.openlandcontracts.org/contract/ocds-591adf-LR8570774189OL/view#/text
- http://www.openlandcontracts.org/contract/ocds-591adf-LR9587702520OL/view#/text 
- http://www.openlandcontracts.org/contract/ocds-591adf-LR9409426421OL/view#/text 
- http://www.openlandcontracts.org/contract/ocds-591adf-LR6929495432OL/view#/text 
- http://www.openlandcontracts.org/contract/ocds-591adf-CD1183226112OL/view#/text
- http://www.openlandcontracts.org/contract/ocds-591adf-CD0848066778OL/view#/text 

Note that I haven't checked all of the contracts on the site. For the contracts listed above, the backend indicates that the text version of the contract should not be showing. 

![screen shot 2016-01-13 at 14 08 24](https://cloud.githubusercontent.com/assets/14910764/12304808/77a47eec-b9ff-11e5-9042-4397d6ecd486.png)

Not sure if this is related, but neither the text nor PDF is displaying for this contract (screenshot of error message below) 
http://www.openlandcontracts.org/contract/ocds-591adf-LR6527070028OL/view 

![screen shot 2016-01-13 at 14 16 49](https://cloud.githubusercontent.com/assets/14910764/12304997/7569875c-ba00-11e5-927d-9a20cd55749d.png)

cc @KaitlinCCSI

**Comment by hello-deepak** [comment] 2016-01-14 11:24
Recenty we have updated the api but the changes of "is_ocr_reviewed" has not reflected in subsite .
 So we have updated subsites and the problem is fixed now.

**Closed by hello-deepak** 2016-01-14 11:24 UTC
