### ISSUE TITLE
Error: "looks like something went wrong"

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#847] opened 2016-04-04 12:36 UTC
From our annotator:

I have been annotating this contract the past two days- http://resourcecontracts.elasticbeanstalk.com/contract/790. 

I am now unable to access it. Everytime I now try to open the page, it says something went wrong. 

![image](https://cloud.githubusercontent.com/assets/12913915/14248032/4c439950-fa40-11e5-940b-a81827948c13.png)

**Comment by anderspeders** [comment] 2016-04-04 14:19
@anjesh @manishgs Could you follow up here?

**Comment by upasna01** [comment] 2016-04-05 03:51
The issue is fixed now.

**Closed by upasna01** 2016-04-05 03:51 UTC
