### ISSUE TITLE
Additional search paramaters

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#217] opened 2015-08-26 06:54 UTC
There should be another search item titled ‘Industry’ (mining, oil, gas, land, forestry, etc) allowing for a more refined search? 

Another option is to extend the 'ResourceContracts' drop-down to include mining, oil, gas, land, forestry, etc.

**Comment by anderspeders** [comment] 2015-08-31 14:05
Add the following search terms to the UI: 
- "Company name"
- "Corporate group"
- "Contract type"

**Comment by anjesh** [comment] 2015-09-07 08:28
duplicate of #253

**Closed by anjesh** 2015-09-07 08:28 UTC
Labels: feature request, Front end / UI - general category, Metadata
