### ISSUE TITLE
Enhancing site for low web connectivity

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#596] opened 2015-10-26 21:46 UTC
@anderspeders is there any more work planned on enhancing the site in low web connectivity environments?

If not could you describe what the site currently does offer for such environments?

**Comment by anjesh** [comment] 2016-01-15 11:26
Should be fixed to certain extend. Details here https://github.com/NRGI/resourcecontracts.org/issues/485#issuecomment-170831573
duplicate of #485

**Closed by anjesh** 2016-01-15 11:26 UTC
