### ISSUE TITLE
Add geo-coordinates to metadata form - to enable PH-EITI map. Field name: deliveryLocation

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#447] opened 2015-10-02 21:31 UTC

**Comment by charlesyoung** [comment] 2015-10-06 13:32
Was also asked (adding coords) at the Pretoria Workshop.

**Comment by anderspeders** [comment] 2015-10-06 16:16
This issue will need to fullfil the following requirements / users: 

a) On single project coordinated: 
- Be compliant with the Open Contracting Data Standard and ResourceProjects.org on project location 

See: https://github.com/open-contracting/standard/issues/250

b) On multiple geo-coordinates for mapping contract areas 
Follow guidelines from technical scoping delivered by Cadasta.org

**Comment by charlesyoung** [comment] 2015-11-02 13:21
Is this still scheduled for Sprint #11?

**Comment by anjesh** [comment] 2015-12-11 09:07
The following metadata are to be captured for project location

* City
* County
* State
* Country [has already been captured in the metadata now]
* Project Areas (There will be provision for multiple project areas, each area will have set of points - lat-lon, each lat/lon will be captured in degree(DD), minutes(MM), seconds(SS)). See https://github.com/NRGI/resourcecontracts.org/issues/136

![image](https://cloud.githubusercontent.com/assets/120488/11739686/6c5ebbd2-a015-11e5-9842-48f77c6fe7f9.png)

The following metadata will be captured alongside other contracts metadata. However we can think if there could be another page where the location information are captured so as not to overwhelm the uploaders. They will only add project location information if available. 

The location data will be indexed in the Elasticsearch engine when the particular contract is published, and is available in contract API. The location data will be indexed in the form of geojson, the deg,min,sec data will be converted to decimal degree format (DD.dddd) using DD.dddd = DD + (MM/60) + (SS.SS/3600). 

There could be a separate API for locations only for mapping all the contracts areas later.

**Comment by charlesyoung** [comment] 2015-12-11 10:03
Couple questions:

1. Will the location info be captured from drop-downs?
2. How easy will it be to change the location levels? PH for instance have the following three levels; Region, Province and Municipality. (see below xls)
3. Is the 'add more area' for multi-part shapes? 
4. Does the coord capture process tie in with the work Cadasta has been doing? 
5. The point data will obviously be converted to polygons
6. Do we do any validations on the coord entry? 
7. How will this be presented on the public RC site?

[PH Locations.xlsx](https://github.com/NRGI/resourcecontracts.org/files/59232/PH.Locations.xlsx)

**Comment by anjesh** [comment] 2015-12-11 10:42
Couple questions:

> Will the location info be captured from drop-downs?

We need to have the codelist for all the states/counties/cities countries, if available then we can have the dropdown, perhaps have the combination of dropdown and free-text.

> How easy will it be to change the location levels? PH for instance have the following three levels; Region, Province and Municipality. (see below xls)

For the location level, the one ph has is the just the labels. The one i am using is from the cadasa document. I have left out ward, thinking it's too detailed. But this is on for discussion. 

> Is the 'add more area' for multi-part shapes?

Yes, see the image here https://github.com/NRGI/resourcecontracts.org/issues/136 

> Does the coord capture process tie in with the work Cadasta has been doing?

Yes, as per document "....employees should transcribe the degrees, minutes and seconds (DD° MM’ SS.SS”) of each point coordinate in a contract area or subarea. Transcribed data will then be transformed into decimal degrees format (DD.ddd) using the formula DD.dddd = DD + (MM/60) + (SS.SS/3600)...." 

> The point data will obviously be converted to polygons

Yes if the data points are entered properly, they will be converted to polygons or lines. 

> Do we do any validations on the coord entry?

We will have that. What values does DD, MM and SS take, we have limit to those possible numbers. 

> How will this be presented on the public RC site?

This is still on for discussion. This issue is particularly for capturing the data and sending through the API. On the other note, I see these locations being shown in the map when viewing the contract summary. Also there could a map in the advanced search page, where all the project locations are drawn and the search will filter out contracts location based on the selected criteria (e.g. we can only see the locations of coal contracts in the world map).

**Comment by charlesyoung** [comment] 2015-12-11 12:06
Sounds good. 

The DMS validations should be as follows. 

1. Latitude decimal values range between -90 to 90
2. Longitude decimal values range between -180 to 180
3. Degrees range between 0 – 60 (whole number)
4. Minutes range between 0 – 60 (whole number)
5. Seconds range between 0 – 59.99 (decimal number)

We should also possibly check that the coords fall within the relevant country boundaries.

**Comment by charlesyoung** [comment] 2015-12-14 06:17
There also needs to be an option to select North/South for the latitudes and East/West for the longitudes.

**Comment by charlesyoung** [comment] 2015-12-14 09:34
Can you please send me the link to the Cadasta doc you mention above? The one I have doesn't mention the PH location levels. 

Also will UTM to DMS conversions be handled separately to above process?

**Comment by jpmckinney** [comment] 2015-12-14 17:47
Instead of City, County, State (or Municipality, Province, Region) I recommend using more standardized terms:

The vCard family of terms:

* [vCard `ADR`](http://tools.ietf.org/html/rfc6350): locality, region, country
* [Schema.org `PostalAddress`](http://schema.org/PostalAddress): locality, region, country

Or the INSPIRE family of terms:

* [INSPIRE](http://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_AD_v3.0.1.pdf):
* [W3C ISA Programme Location Core Vocabulary](http://www.w3.org/ns/locn.html): postName, adminUnitL2, adminUnitL1

Basically, all popular international standards limit themselves to 3 admin levels: country, region, locality. This issue discusses having a 4th intermediate level, but I've never seen it implemented across jurisdictions. The problem is that as you add more granularity, you lose comparability across jurisdictions. INSPIRE allows for 6 admin units, but if you go that deep it's all apples and oranges, e.g.

* ADM1 United Kindom, ADM2 Great Britain, ADM3 England, ADM4 Oxfordshire, ADM5 Oxford 
* ADM1 Canada, ADM2 Ontario, ADM3 Peel, ADM4 Mississauga, ADM5 Ward 1

But usually what you want is a simple hierarchy where you know that you are comparing city to city and not city to ward or city to county...:

* country United Kingdom, region England, locality Oxford
* country Canada, region Ontario, locality Mississauga

**Comment by jpmckinney** [comment] 2015-12-14 17:51
I also don't think this field matches the semantics of `deliveryLocation`. `deliveryLocation` is so-named because if a supplier is contracted to deliver a fighter jet to an airbase, then the *delivery* location is what matters (the airbase), not the location of its manufacture or design or whatever.

However, for resources, what are being delivered are royalties, fees, bonuses, production shares, etc. The location of the *delivery* is unimportant (if there's really a definable location for where a royalty is delivered). For resources, what matters is the location of *production* (or whatever term you prefer).

So, the semantics are not the same. It's confusing to overload `deliveryLocation` with this distinct meaning.

**Comment by jpmckinney** [comment] 2015-12-15 19:00
Note that there's agreement in the OC issue that `deliveryLocation` is incoherent for extractives: https://github.com/open-contracting/standard/issues/250#issuecomment-146414233

**Closed** 2017-01-11 11:59 UTC
Labels: Metadata, RC country request
