### ISSUE TITLE
Key Clause searches Excel download 

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#1202] opened 2019-06-26 15:05 UTC
## Why
When I try to download a selection of annotated contracts as spreadsheet the download button returns an empty dataset. 

Example - I am downloading from this slice: https://resourcecontracts.org/search?q=&annotation_category%5B%5D=Stabilization

Empty spreadsheet returned: ![image](https://user-images.githubusercontent.com/1101585/60191346-2b943300-9802-11e9-97d7-0a96d6bf9980.png)

**Comment by charlesyoung** [comment] 2020-09-16 09:37
@anjesh can you please look at this and let me know how much time will be required.

**Comment by charlesyoung** [comment] 2020-09-29 16:00
@anjesh can you please look at this and let me know how much time will be required.

**Comment by charlesyoung** [comment] 2020-10-20 14:22
@anjesh how much time will it take to fix this issue? 

I want to group it with #1313

**Comment by anjesh** [comment] 2020-10-21 14:39
Sorry for the late response @charlesyoung . Around a day work to debug, fix, deploy and testing.

**Comment by charlesyoung** [comment] 2020-10-21 17:50
Thanks @anjesh 

I will budget 8 hours for this activity.

**Comment by charlesyoung** [comment] 2020-11-09 17:54
@anjesh can you please remind me if the general search and annotations search results xls export includes the same columns. Did we ever have a separate annotations download option?

**Comment by anjesh** [comment] 2020-11-11 06:52
I don't remember having separate annotation download except in the clips feature.

**Comment by surazneupane** [comment] 2020-12-16 07:32
@charlesyoung can you verify in staging server if the spreadsheet is not empty and all data are correct in spreadsheet? Thanks !

**Comment by charlesyoung** [comment] 2020-12-16 08:42
Thanks. I notice that the Annotation Category and Annotation Text columns are empty when exporting the data on below search. 

https://staging.resourcecontracts.org/search/group?q=&key_clause%5B%5D=Stabilization

Please remember to also look at #1313 while working on this ticket because it includes deleting, moving and renaming column names.

**Comment by charlesyoung** [comment] 2020-12-16 08:43
A reminder that #1313 is only for RC.

**Comment by charlesyoung** [comment] 2020-12-16 13:19
@surazneupane can I ask that you make the top row (column names) bold, please.

**Comment by surazneupane** [comment] 2020-12-16 14:48
@charlesyoung  before that can you please check if the document is not empty and all data are correct in spreadsheet in staging server. Thanks!

**Comment by charlesyoung** [comment] 2020-12-16 16:59
Like mentioned above Annotation Category and Annotation Text columns are empty

**Comment by surazneupane** [comment] 2020-12-16 17:04
![SmartSelect_20201216-224857_Office](https://user-images.githubusercontent.com/37624741/102381102-e9ac0d80-3ff0-11eb-92f8-3c71d7e4fb1f.jpg)
@charlesyoung  are you sure that fields are empty?

**Comment by charlesyoung** [comment] 2020-12-16 17:16
I'm finding it difficult to test on Staging. 

When searching on the Stabilisation clause it presents 50 results but actually, some of those docs don't have any annotations. I also cannot test the annotation text column properly. We also had issues testing the country page grouping yesterday on dirty data. 

How can we resolve this issue? Can you copy the Prod DB over the Staging DB so that I can run proper tests?

cc @anjesh

**Comment by iprunache** [comment] 2020-12-16 17:32
@charlesyoung we would be able to clone the production data and switch staging to using it if you think that's a workable solution. We would also have to reindex all data to Elasticsearch which takes up to half a day.

Please create an issue for this if you decide on doing it.

**Comment by iprunache** [comment] 2020-12-16 17:34
Just to make it more clear, reindexing involves a long running automated task, not a half a day of effort.

**Comment by charlesyoung** [comment] 2020-12-16 17:36
Understood, thanks @iprunache 

Will there be an ES cost when running the reindexing? 

Can we take a couple of countries and not the entire DB?

**Comment by iprunache** [comment] 2020-12-16 17:40
@charlesyoung there wouldn't be any extra costs with infrastructure.

Why just a couple of countries? Are you thinking of optimizing costs or time to get it done? The indexing task can run overnight without supervision. It shouldn't be an issue to clone the full data.

**Comment by charlesyoung** [comment] 2020-12-16 17:43
It was to try optimize costs but that doesn't seem an issue. Can you please go ahead and clone, switch and reindex. Thanks

**Comment by iprunache** [comment] 2020-12-16 19:23
@charlesyoung I cloned the production data onto the staging env. In the end I did not reindex the data but just also cloned the Elasticsearch index.

Let me know if it doesn't work well for you. And take care not to confuse it with the prod environment :)

**Comment by surazneupane** [comment] 2020-12-17 04:14
@charlesyoung  Does it looks good in staging server now? can you verify it ? Thanks !

**Comment by charlesyoung** [comment] 2020-12-17 06:34
Many thanks @iprunache

**Comment by charlesyoung** [comment] 2020-12-17 06:57
Can you please remove the semi-colons were not needed like shown below. Semi-colons should only be used to separate metadata. 

![image](https://user-images.githubusercontent.com/13888372/102452670-64057d80-4043-11eb-8e4e-c62a4ea19159.png)

I'm confused by what is exported. As an example, I ran a search for the annotated tag capital gains tax. 

https://staging.resourcecontracts.org/search/group?q=&key_clause%5B%5D=Capital+gains+tax

The output, however, includes more than capital gains tax with income tax: other, income tax: rate, etc also added to the list. The annotation text column notes some of the info but doesn't include the capital gains tax summary of Art. 3.5 C. 



![image](https://user-images.githubusercontent.com/13888372/102453535-0eca6b80-4045-11eb-9a48-f8b52476c7cf.png)

**Comment by surazneupane** [comment] 2020-12-17 13:29
@charlesyoung  Can you verify if all okay at staging server . Thanks !

**Comment by charlesyoung** [comment] 2020-12-18 06:34
Looking good thanks. 

I would suggest that you first complete #1313 before moving this to the Prod site.

**Comment by charlesyoung** [comment] 2021-01-11 13:46
None of the PDF documents are available on the Staging site. 

![image](https://user-images.githubusercontent.com/13888372/104189966-11da3100-5424-11eb-9166-0dd62a60f30b.png)

**Comment by charlesyoung** [comment] 2021-01-11 13:52
@surazneupane is below duplicated because 6 pages have been annotated? 

![image](https://user-images.githubusercontent.com/13888372/104190188-641b5200-5424-11eb-9cb6-77d291a46303.png)

![image](https://user-images.githubusercontent.com/13888372/104190539-ed328900-5424-11eb-8d69-6735d71da341.png)

**Comment by iprunache** [comment] 2021-01-11 17:13
@charlesyoung about the missing documents, that's because I did not also clone the AWS production bucket holding the contract pages. There's a lot of data there and I was not sure if it's critical.

I can start a process to clone the bucket to staging early next week if it's not a blocker for you right now. Would that work?

**Comment by charlesyoung** [comment] 2021-01-12 07:11
Thanks @iprunache, sounds good. 

Just checking that there won't be any additional ABBYY, etc costs?

**Comment by iprunache** [comment] 2021-01-12 08:10
@charlesyoung there would be an extra cost of about $4-$6 per month for the S3 storage. No extra cost from Abbyy.

**Comment by charlesyoung** [comment] 2021-01-12 09:33
OK thanks

**Comment by charlesyoung** [comment] 2021-01-12 09:46
@surazneupane can you please hold on doing work on this ticket and #1313. I need to discuss this internally but will it be possible not to add the actual summary text but only the relevant clause article/s as a hyperlink (see below example on row 2). The issue is that for RC going forward summaries won't be captured with only the clause article captured. This might also help with the current problem of presenting long summaries in the xls. 

![image](https://user-images.githubusercontent.com/13888372/104297656-caa77b00-54cb-11eb-95f5-3240a60bc66f.png)

**Comment by charlesyoung** [comment] 2021-01-13 07:42
@surazneupane OK I have chatted to the internal NRGI team. 

Will it be possible to only include the article reference as a hyperlink in the xls and not show the summary text (RC only)? As mentioned we have stopped adding summary text for RC when annotating. 

![image](https://user-images.githubusercontent.com/13888372/104420926-4dd7d800-5583-11eb-817d-05d2f971057b.png)

**Comment by charlesyoung** [comment] 2021-01-14 08:58
@surazneupane just wondering if there is any feedback on this ticket?

**Comment by surazneupane** [comment] 2021-01-15 07:44
@charlesyoung  little bit confused about how the links should be added ? should we add the link to the page of the contract for each article_reference ?. 
for example : [](https://resourcecontracts.org/contract/ocds-591adf-3429963881/view#/pdf)

**Comment by charlesyoung** [comment] 2021-01-15 07:47
Can we add the article link eg Art. 4.2 in the xls so that a user can click on the hyperlink and be taken to the relevant clause?

**Comment by surazneupane** [comment] 2021-01-15 09:51
@charlesyoung  to add multiple hyperlink in a single cell is technically impossible for article_refrence .
but there are multiple ways we can do to add hyperlinks in xls :
1. adding actual multiple hyperlink in cell . for example (https://resourcecontracts.org/contract/ocds-591adf-1266553396/view#/pdf/page/61/annotation/36562 ,  https://resourcecontracts.org/contract/ocds-591adf-1266553396/view#/pdf/page/76/annotation/36638) seperated with comma .
2. or , we can only populate only one article_refrence with hyperlink in each cell that will repeat same document for the key clauses.
cc @anjesh  @man-git007

**Comment by charlesyoung** [comment] 2021-01-15 10:21
Thanks @surazneupane. I thought it might be technically difficult to add multiple hyperlinks in a single cell. 

I will need to discuss this internally but will it be possible to mask the URLs in option 1. So for example not show the entire URL in the xls but use the page number text or something else.

**Comment by surazneupane** [comment] 2021-01-15 10:26
@charlesyoung didnot understand.  Can you please provide an example . Thanks !

**Comment by charlesyoung** [comment] 2021-01-15 10:39
So something like below. Don't show the entire URL but have it hyperlink the actual page number or some other text. I'm assuming that it won't be possible but just asking because some clauses could have 5 tags which then makes the column very long with the 5 URLs. 

![image](https://user-images.githubusercontent.com/13888372/104714813-56b8dd00-572e-11eb-9fc8-a888c51dc5d3.png)

**Comment by surazneupane** [comment] 2021-01-15 11:14
@charlesyoung  it will be technically impossible  to add multiple hyperlink to multiple text in a single cell .

**Comment by charlesyoung** [comment] 2021-01-15 11:29
OK let me get back to you.

**Comment by charlesyoung** [comment] 2021-01-16 15:14
@surazneupane can you open [this ](https://resourcecontracts.org/contract/ocds-591adf-1266553396/view#/pdf/page/76/annotation/36638)link as a hyperlink in Excel. I get below error. 

![image](https://user-images.githubusercontent.com/13888372/104815582-19cc1380-581e-11eb-94fd-6bf2cada1187.png)

**Comment by surazneupane** [comment] 2021-01-18 03:45
yes it is working @charlesyoung

**Comment by charlesyoung** [comment] 2021-01-18 06:04
Can you please send me an example xls with the link added because I cannot get it to work.

**Comment by surazneupane** [comment] 2021-01-18 07:12
@charlesyoung  please provide your email so that i can send you sample xls files with link added . and also the examples how the links can be added in xls . Thanks

**Comment by charlesyoung** [comment] 2021-01-18 07:15
charlesandersonyoung@gmail.com

**Comment by charlesyoung** [comment] 2021-01-18 08:18
I get an error. 

![image](https://user-images.githubusercontent.com/13888372/104889140-6cb8de80-5976-11eb-92be-a6c01762fb89.png)

**Comment by surazneupane** [comment] 2021-01-18 08:31
Can't figure out what is causing the error . But on my machine I am taken
to the requested link in the browser when I click on the link .

**Comment by charlesyoung** [comment] 2021-01-18 08:59
There does seem to be an issue using the # symbol in Excel hyperlinks. What OS are you using? Can you test on other computers?

**Comment by charlesyoung** [comment] 2021-01-18 09:06
I'm running Windows. I get a 'Cannot locate the Internet server or proxy server' error when trying to open the links on an Apple machine.

**Comment by charlesyoung** [comment] 2021-01-19 06:14
@surazneupane just to let you know that I asked a couple of my friend to open the xls hyperlinks and they all had the same problem. Can you please take a look at this today, if you have time, because we need to wrap up Sprint 27.

**Comment by man-git007** [comment] 2021-01-19 08:41
@charlesyoung As you are suggesting to replace the hyperlinks with the **page number or some text**, this cannot be done in excel as multiple links in a cell is not possible, however, we can have the actual links in the cell and this will indeed as you have mentioned could be long. Shall we proceed with the actual links in the cell?.

Also regarding the links which are not opened on your side. Could you please mention the excel software version. As it seems to be a third party application issue rather than the subsite issue.

cc @anjesh @surazneupane

**Comment by charlesyoung** [comment] 2021-01-19 08:51
Thanks @man-git007 

I don't want multiple links in a cell but only 1. All I want is an Article i.e. Art. 1.2 hyperlinked in a cell. If there are more than 1 Article for a specific clause then only the first Article should be added to the doc. 

There is a known issue with using # in a hyperlink as well as the proxy server issue noted above which a Google search will reveal. 

Can I suggest a Skype call today to fast-track the conversation?

**Comment by man-git007** [comment] 2021-01-19 09:53
@charlesyoung OK we will add the first article if there are multiple. As for the **#** hyperlink, the issue in the MS-Excel application only. We can have a skype meeting now if required.

cc @surazneupane

**Comment by charlesyoung** [comment] 2021-01-19 09:55
But all the users will be using Excel to open the links. I have just sent you a Skype request.

**Comment by man-git007** [comment] 2021-01-20 08:58
@charlesyoung We have deployed this in the [live](https://resourcecontracts.org/) server. Please check once.

Since there is an issue with **hyperlink** we have not added links in the article reference, the cell will have the article reference as a plain text.

For the  **hyperlink** issue in Excel, let's create a separate issue.

cc @anjesh @surazneupane

**Comment by charlesyoung** [comment] 2021-01-20 09:21
Thanks but not sure why you moved it to Prod because it still needs work. 

Vitamin is looking at the hyperlink issue but we will need to apply updates to the xls once the links are working. 

I thought we will only move #1313 to Prod.

**Comment by man-git007** [comment] 2021-01-20 09:48
@charlesyoung OK we will remove the key clause feature from the production for now.

cc @surazneupane

**Comment by surazneupane** [comment] 2021-01-21 07:00
@charlesyoung  we have currently removed the key clause feature from production please verify it. Thanks !

**Comment by charlesyoung** [comment] 2021-01-25 07:31
@surazneupane please see below an example of the what is required. Let me know if you understand the instructions.

[Clause hyperlink - examples.xlsx](https://github.com/NRGI/resourcecontracts.org/files/5864868/Clause.hyperlink.-.examples.xlsx)

.

**Comment by man-git007** [comment] 2021-01-29 10:24
@charlesyoung The changes have been made to the [staging](https://staging.resourcecontracts.org/search/group?q=&key_clause%5B%5D=Bonuses&key_clause%5B%5D=Confidentiality) server. Please verify it. If any issue please let me know.

**Comment by charlesyoung** [comment] 2021-01-29 10:45
Some points on running a simple search (1 clause). 
- The key clause only needs to be noted once, in the 'Key Clause' column, not like 'Confidentiality,Confidentiality' if more than 1 clause has been tagged. Should just be 'Confidentiality'
- When duplicates are present, of the same clause, like 'Confidentiality', then the first tagged paged needs to be hyperlinked. It seems that the last tagged page is hyperlinked in the xls like what was done for its contract when searching for the 'Confidentiality' clause. https://resourcecontracts.org/contract/ocds-591adf-2561344209/view#/pdf/page/69/tagged/32041

**Comment by charlesyoung** [comment] 2021-01-29 11:01
One more thing. 

For the clipping xls hyperlinks the annotation box with the clause details are shown. Can we do the same here because otherwise if more that one clause is tagged on the same page the user won't know which one relates to their search?

**Comment by charlesyoung** [comment] 2021-02-01 13:52
@man-git007 just checking that you have the time to look at above comments? We need to try to get this functionality implemented as soon as possible.

**Comment by man-git007** [comment] 2021-02-02 08:58
@charlesyoung I have made the changes and deployed them in the [staging](https://staging.resourcecontracts.org/search/group?q=&key_clause%5B%5D=Environmental+protections&key_clause%5B%5D=Infrastructure&key_clause%5B%5D=Location) server. Please verify.

**Comment by charlesyoung** [comment] 2021-02-02 09:06
Many thanks, @man-git007 

Let me run this past the internal team. I will get back to you by tomorrow.

**Comment by charlesyoung** [comment] 2021-02-08 09:52
OK all looking good. 

Can I, however, ask that you delete the following fields form the Key Clause xls _(Note: Only for RC and not for the general documents xls download)._ 

- OCID
- Document Type
- Gov Entity
- Company Address
- Jurisdiction of Incorporation
- Registration Agency
- Company Number
- Corporate Grouping
- Participation Share
- Open Corporates Link
- Incorporation Date
- Operator
- Project Title
- Project Identifier
- License Name
- License Identifier
- Source Url
- Disclosure Mode
- Retrieval Date

**Comment by man-git007** [comment] 2021-02-10 08:29
@charlesyoung The changes you have requested have been done and deployed in the staging server. Please verify

**Comment by charlesyoung** [comment] 2021-02-10 08:36
Thanks. Looks good but will need to confirm with Nicola. 

One thing, I get below message which is new. 

![image](https://user-images.githubusercontent.com/13888372/107484710-7f948c80-6b8b-11eb-9ea4-a9ee624d5b15.png)

**Comment by man-git007** [comment] 2021-02-10 08:39
@charlesyoung This might be due to the addition of a link in the View Clause cell.

**Comment by charlesyoung** [comment] 2021-02-10 08:41
Nope, the clause link has been there for a while and I have never seen this before. 

This is the first time this has happened and we need to try resolve because users will be concerned to open the xls.

**Comment by man-git007** [comment] 2021-02-10 10:05
@charlesyoung Please check now.

**Comment by charlesyoung** [comment] 2021-02-10 10:06
Fixed. What was the issue?

**Comment by man-git007** [comment] 2021-02-10 10:25
> Fixed. What was the issue?

The View Clause link was not proper on the hover of the cell.
![Screenshot from 2021-02-10 16-10-09](https://user-images.githubusercontent.com/23434972/107497299-81297900-6bba-11eb-873c-b923ab8fd62c.png)

**Comment by man-git007** [comment] 2021-02-10 10:45
@charlesyoung If all good, can we send this to production?

**Comment by charlesyoung** [comment] 2021-02-10 10:46
Just need Nicola to confirm later today.

**Comment by charlesyoung** [comment] 2021-02-15 06:35
@man-git007 please move this to the Prod site. Thanks

**Comment by man-git007** [comment] 2021-02-15 08:00
@charlesyoung The changes have been deployed to the [live](https://resourcecontracts.org/) server. Please check

**Comment by charlesyoung** [comment] 2021-02-15 09:56
Thanks

**Closed by charlesyoung** 2021-02-15 09:56 UTC
