### ISSUE TITLE
MT error - "Assignment could not be approve."

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#581] opened 2015-10-24 14:28 UTC
System not letting me approve pages that have been processed in MT
http://resourcecontracts-demo1.elasticbeanstalk.com/mturk/36/1109
![screen shot 2015-10-24 at 10 26 10 am](https://cloud.githubusercontent.com/assets/12913915/10710936/ed5d14ce-7a39-11e5-9ffa-d9846dd4ac84.png)
![screen shot 2015-10-24 at 10 27 25 am](https://cloud.githubusercontent.com/assets/12913915/10710937/f16a43c0-7a39-11e5-9d9c-9c382b6a0037.png)

**Comment by anjesh** [comment] 2015-11-05 08:26
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/626

**Closed by anjesh** 2015-11-05 08:26 UTC
