### ISSUE TITLE
Color of Annotation cluster categories

### ISSUE THREAD

**Issue by jedm** [NRGI/resourcecontracts.org#907] opened 2016-06-03 23:59 UTC
The green color in these cluster categories is from OLC. It is the only place green appears in RC and should be changed to the orange color being used as a highlight across RC.

Also please change "By Page" and "By Topic" buttons to the respective site colors for RC and OLC (so, orange for RC, green for OLC).

Request is for consistency and also because of forthcoming color request re. Clips. Thanks!

![annotations_cats](https://cloud.githubusercontent.com/assets/2153664/15796049/907691ae-29ac-11e6-951b-195c7a9aad0d.png)

**Comment by upasna01** [comment] 2016-06-16 11:40
The issue is fixed now, please do verify.

http://www.resourcecontracts.org/contract/ocds-591adf-BO5403171133RC/view
![907](https://cloud.githubusercontent.com/assets/11477899/16115525/3f467fe8-33e7-11e6-9033-78d94d21a666.png)

**Closed by upasna01** 2016-06-16 11:40 UTC
Labels: 3 - Done, Front end / UI - general category, UI - Contract page
