### ISSUE TITLE
Project location reference information / geo-location latitude longitude

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#488] opened 2015-10-07 15:05 UTC
Philippines want to capture project location reference (region, province and municipality) information as metadata. Could this be added in later Sprints?

**Comment by anjesh** [comment] 2015-12-11 09:03
The following metadata are to be captured for project location

* City
* County
* State
* Country [has already been captured in the metadata now]
* Project Areas (There will be provision for multiple project areas, each area will have set of points - lat-lon, each lat/lon will be captured in degree(DD), minutes(MM), seconds(SS)). See https://github.com/NRGI/resourcecontracts.org/issues/136

![image](https://cloud.githubusercontent.com/assets/120488/11739686/6c5ebbd2-a015-11e5-9842-48f77c6fe7f9.png)

The following metadata will be captured alongside other contracts metadata. However we can think if there could be another page where the location information are captured so as not to overwhelm the uploaders. They will only add project location information if available. 

The location data will be indexed in the Elasticsearch engine when the particular contract is published, and is available in contract API. The location data will be indexed in the form of geojson, the deg,min,sec data will be converted to decimal degree format (DD.dddd) using DD.dddd = DD + (MM/60) + (SS.SS/3600). 

There could be a separate API for locations only for mapping all the contracts areas later.

**Comment by anjesh** [comment] 2015-12-11 09:08
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/447

**Closed by anjesh** 2015-12-11 09:08 UTC
Labels: Country requests, Metadata
