### ISSUE TITLE
Map RC API output to OCDS API

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#614] opened 2015-10-28 16:33 UTC

**Comment by anjesh** [comment] 2015-10-30 11:01
http://nbviewer.ipython.org/gist/timgdavies/41fd60770cbecb2fdbd6

**Comment by anjesh** [comment] 2016-05-24 04:41
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/201

**Closed by anjesh** 2016-05-24 04:41 UTC
Labels: Metadata
