### ISSUE TITLE
Add annotation in the search result

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#322] opened 2015-09-16 18:50 UTC
![image](https://cloud.githubusercontent.com/assets/1101585/9914817/bb40b87c-5c81-11e5-8805-b97dcc1e2989.png)

**Comment by anjesh** [comment] 2016-01-18 07:32
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/761

**Closed by anjesh** 2016-01-18 07:32 UTC
Labels: UI - Advanced search view
