### ISSUE TITLE
BUG: Upside down / back to front PDF on backend

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#805] opened 2016-03-07 16:32 UTC
This error happens almost every time I click back or forth quickly on the back end. It is impairing our ability to review contracts quickly. @anderspeders 

![image](https://cloud.githubusercontent.com/assets/12913915/13575699/33f62816-e458-11e5-98e4-7c8fd8a9b9f9.png)

**Comment by anderspeders** [comment] 2016-03-08 03:00
@anjesh @manishgs: Can you please check what is happening here?

This example seems to relate to contract 924

**Comment by anjesh** [comment] 2016-05-23 07:58
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/879

**Closed by anjesh** 2016-05-23 07:58 UTC
