### ISSUE TITLE
Admin page for editing FAQ/ Resources, etc. pages down 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#917] opened 2016-06-21 20:01 UTC
Hi there, 

I've been trying to edit the OLC FAQ, About and Resources pages but am getting an error when I try to do so (screenshot below). Assuming this is a bug? 

Thanks, 
Jesse 

(cc @SamCCSI or @KaitlinCCSI can you label as a bug please? thanks) 

![screenshot 2016-06-21 15 57 23](https://cloud.githubusercontent.com/assets/14910764/16244287/47b26a80-37c9-11e6-8d7f-443a8eb801fd.png)

**Comment by upasna01** [comment] 2016-06-22 11:36
The issue is fixed now.

**Closed by upasna01** 2016-06-22 11:36 UTC
Labels: bug
