### ISSUE TITLE
Add OCR-evaluation status to internal dashboard

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#180] opened 2015-08-08 22:46 UTC
Add the evaluation status from the OCR-process to the internal dashboard: 
- Accepted
- Needs editing
- Rejected - needs transcription

![add text status](https://cloud.githubusercontent.com/assets/1101585/9152588/a06d9e22-3dfd-11e5-9c0c-f39fa898b956.JPG)

**Comment by anderspeders** [comment] 2015-08-12 15:56
Unless this is complate - I suggest that we postpone this until the next sprint.

**Comment by anjesh** [comment] 2015-08-31 07:15
duplicate of #212

**Closed by anjesh** 2015-08-31 07:15 UTC
Labels: 3 - Done
