### ISSUE TITLE
Enforce unique contract names?

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#658] opened 2015-11-13 10:28 UTC
Should we allow for contracts with the same name? 

![image](https://cloud.githubusercontent.com/assets/13888372/11143939/aece9548-8a01-11e5-88c1-20ca38379c82.png)

**Comment by anderspeders** [comment] 2015-11-13 14:12
Given that the OCID and internal doc ID act as unique id there is not an issue with this as such. I am unsure if this will arise to become an actual issue which will require a technical fix.

**Comment by jpmckinney** [comment] 2015-12-14 15:05
Renaming issue, otherwise it is duplicate of #649

**Comment by anjesh** [comment] 2016-01-15 10:32
We check for the pdf file for duplication. So there can't be two contracts with the same pdfs but they can have same contract name. This issue can be superceded by https://github.com/NRGI/resourcecontracts.org/issues/649. There has been discussion of standarding title.

**Closed by anjesh** 2016-01-15 10:32 UTC
Labels: question
