### ISSUE TITLE
Resource list

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#219] opened 2015-08-26 08:27 UTC
A standard resource list should be created. 

Example below. 

![image](https://cloud.githubusercontent.com/assets/13888372/9488821/c36f3114-4bdc-11e5-9223-5f0a5ac93edb.png)

**Comment by anjesh** [comment] 2015-08-31 08:27
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/205 
List is prepared and shared in google docs. Further discussion there.

**Closed by anjesh** 2015-08-31 08:27 UTC
Labels: Priority
