### ISSUE TITLE
Document types

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#832] opened 2016-03-17 12:56 UTC
1. ‘Stabilization Agreement’ was supposed to be deleted but it still remains in the drop down list. Just to confirm that this can be deleted. 
2. Can we change ‘Environmental Impact Assessment’ to ‘Environmental Impact’ so as to conform to the OC standard? 
3. Is there any difference between ‘Social Impact Assessment’ and ‘Social Agreement’? 
4. Should contract annexes not rather be noted as a document type, as it initially was and as noted by OC, than a contract type? 

Details noted in the annotation categories and codelist sheet. 

https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit#gid=1026386158

**Comment by KaitlinCCSI** [comment] 2016-03-22 16:10
There is a difference between Social Impact Assessment and Social
Agreement. cc'ing @Samccsi re the annexes.

On Thu, Mar 17, 2016 at 7:56 AM, Charles Young <notifications@github.com>
wrote:

>
>    1. ‘Stabilization Agreement’ was supposed to be deleted but it still
>    remains in the drop down list. Just to confirm that this can be deleted.
>    2. Can we change ‘Environmental Impact Assessment’ to ‘Environmental
>    Impact’ so as to conform to the OC standard?
>    3. Is there any difference between ‘Social Impact Assessment’ and
>    ‘Social Agreement’?
>    4. Should contract annexes not rather be noted as a document type, as
>    it initially was and as noted by OC, than a contract type?
>
> Details noted in the annotation categories and codelist sheet.
>
>
> https://docs.google.com/spreadsheets/d/15k-7NCkgu1p2eKgWGZnykASLQoa4gR6fOLskV8mdOhY/edit#gid=1026386158
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NRGI/resourcecontracts.org/issues/832>
> ------------------------------
>
> Spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qv0UekC&m=4b374969b1f5&t=20160317&c=s>
> Not spam
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qv0UekC&m=4b374969b1f5&t=20160317&c=n>
> Forget previous vote
> <https://antispam.law.columbia.edu/canit/b.php?i=01Qv0UekC&m=4b374969b1f5&t=20160317&c=f>
>



-- 


*KAITLIN Y. CORDES*

*Head: Land and Agriculture**Columbia Center on Sustainable Investment*
Columbia Law School - The Earth Institute, Columbia University
435 West 116th St. New York, NY 10027
| +1 (917) 658 5172
| kaitlin.cordes@law.columbia.edu
| www.ccsi.columbia.edu | @CCSI_Columbia <https://twitter.com/CCSI_Columbia>
 | @kaitlincordes <https://twitter.com/kaitlincordes>

**Comment by SamCCSI** [comment] 2016-03-22 19:06
@charlesyoung The reasoning behind having annexes as a contract type is that they create legally binding obligations (with regard to, for instance, investment commitments, locations of the concession, etc.) and hence should be regarded as a contract type.

**Comment by charlesyoung** [comment] 2016-03-30 11:59
@anjesh can you please remove ‘Stabilization Agreement’ from the document type drop down list as its a contract type.

**Comment by upasna01** [comment] 2016-06-16 12:09
The issue is fixed now, please do verify.
http://admin.resourcecontracts.org/contract/create?parent=101
![832](https://cloud.githubusercontent.com/assets/11477899/16116210/48ba14c8-33eb-11e6-8b23-2023ce633e50.png)

**Comment by upasna01** [comment] 2016-06-16 12:19
The issue is fixed please do verify.

**Closed by upasna01** 2016-06-16 12:19 UTC
Labels: Country requests, Metadata - code list, Needs discussion
