### ISSUE TITLE
Reset button not working?

### ISSUE THREAD

**Issue by KaitlinCCSI** [NRGI/resourcecontracts.org#885] opened 2016-05-18 18:41 UTC
I think reset button is not working. For example: on OLC, I selected French in language box, and saw 22 contracts. I think clicked out of French and hit reset, but my page is still stuck showing the exact same content even though I've clicked on "reset" multiple times.
![screen shot 2016-05-18 at 1 40 30 pm](https://cloud.githubusercontent.com/assets/14825437/15370812/2e86ff52-1cfe-11e6-8189-f4d8ee80e3f7.png)

**Comment by KaitlinCCSI** [comment] 2016-05-18 18:44
Also, if I delete a word in the free text search box and hit reset button, nothing happens, though if I delete the word and then hit enter on my keyboard, it refreshes back to full set of contracts.

**Comment by manishgs** [comment] 2016-05-19 11:31
@KaitlinCCSI @anderspeders 

Reset Button only reset the selected values back to default values in search form,  it will not reset the contract result list.

Do you want to reset contract result when user client on Reset Button?

**Comment by KaitlinCCSI** [comment] 2016-05-19 11:33
Yes, resetting the contract results makes sense to me, so I would be in favor of this. @jedm - is that an intuitive use of a reset button?

**Comment by anderspeders** [comment] 2016-05-19 17:37
Confirming @KaitlinCCSI's suggestion.

**Comment by upasna01** [comment] 2016-06-16 12:05
The issue is fixed now, Please do verify
http://www.resourcecontracts.org/search?q=

**Comment by SamCCSI** [comment] 2016-06-16 13:40
Working nicely for me. Many thanks!

**Comment by SamCCSI** [comment] 2016-06-28 19:46
Reset button not working here: http://www.openlandcontracts.org/search?q=sgsoc

Pressing the button does not delete the search term or bring back the default collection of contracts.

![image](https://cloud.githubusercontent.com/assets/12913915/16429994/7ee7e524-3d47-11e6-9837-790ce96b8379.png)

**Comment by upasna01** [comment] 2016-07-01 12:29
The issue is fixed for olc too, please do verify.

**Closed by upasna01** 2016-07-01 12:29 UTC
Labels: 2 - Working, bug

**Comment by SamCCSI** [comment] 2016-07-01 12:31
Thanks @upasna01 - this works for me now.
