### ISSUE TITLE
Zambia country site

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#1095] opened 2018-02-28 06:27 UTC
Create a Zambia RC country site

**Comment by charlesyoung** [comment] 2018-04-06 11:43
Implement a production country site for Zambia (zambia.resourcecontracts.org) by the 27/04. 

cc @anjesh

**Comment by anjesh** [comment] 2018-04-26 04:40
@adinuca please create staging.zambia.resourcecontracts.org

**Comment by adinuca** [comment] 2018-04-26 05:29
Hi @anjesh , I have created the zambia staging site, but when I tried to test it, I noticed that staging is not working. Do you know what the problem is?
![screen shot 2018-04-26 at 08 28 49](https://user-images.githubusercontent.com/3942821/39287326-df6dcc5a-492b-11e8-951d-7a801540a87b.png)

**Comment by adinuca** [comment] 2018-04-26 05:31
Checked the logs, it looks like Elasticsearch is causing issues:
```
Apr 26 08:26:53 2ca388ae9310 ecs-rc-api-staging-apache2-error.log:  [Thu Apr 26 05:26:53.015227 2018] [:error] [pid 14924] [client 10.0.0.63:35089] PHP Fatal error:  Uncaught exception 'Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException' with message 'No alive nodes found in your cluster' in /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51\nStack trace:\n#0 /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(71): Elasticsearch\\ConnectionPool\\StaticNoPingConnectionPool->nextConnection()\n#1 /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(89): Elasticsearch\\Transport->getConnection()\n#2 /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(188): Elasticsearch\\Transport->performRequest('GET', '/rc_demo_3/meta...', Array, '{"size":0,"aggs...', Array)\n#3 /var/www/rc-api/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array)\n#4 /var/www/rc-api/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\F in /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51
Apr 26 08:26:53 0b12a9710f08 ecs-rc-subsite-staging-var-www-country-tn-storage-logs:  [2018-04-26 05:26:53] lumen.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/country-tn/app/Http/Controllers/SiteController.php:54
Apr 26 08:26:53 0b12a9710f08 ecs-rc-subsite-staging-var-www-country-tn-storage-logs:  [2018-04-26 05:26:53] lumen.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Barryvdh\Debugbar\LaravelDebugbar::modifyResponse() must be an instance of Symfony\Component\HttpFoundation\Response, instance of Illuminate\View\View given, called in /var/www/country-tn/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php on line 60 and defined' in /var/www/country-tn/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php:485
Apr 26 08:26:58 2ca388ae9310 ecs-rc-api-staging-apache2-error.log:  [Thu Apr 26 05:26:58.683111 2018] [:error] [pid 1150] [client 10.0.1.111:47270] PHP Fatal error:  Uncaught exception 'Elasticsearch\\Common\\Exceptions\\NoNodesAvailableException' with message 'No alive nodes found in your cluster' in /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php:51\nStack trace:\n#0 /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(71): Elasticsearch\\ConnectionPool\\StaticNoPingConnectionPool->nextConnection()\n#1 /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(89): Elasticsearch\\Transport->getConnection()\n#2 /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(188): Elasticsearch\\Transport->performRequest('GET', '/rc_demo_3/meta...', Array, '{"size":0,"aggs...', Array)\n#3 /var/www/rc-api/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\\Connections\\Connection->Elasticsearch\\Connections\\{closure}(Array)\n#4 /var/www/rc-api/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\F in /var/www/rc-api/vendor/elasticsearch/elasticsearch/src/Elasticsearch/ConnectionPool/StaticNoPingConnectionPool.php on line 51
```

**Comment by adinuca** [comment] 2018-04-26 06:41
Staging is back up. The hostname that we were to connect to Elasticsearch was no longer available. I have changed it to one that is available. 

I will contact the provider that we are using for Elasticsearch to understand what has happened.

**Comment by adinuca** [comment] 2018-04-26 10:10
Hi @charlesyoung , I will add the production site this week, protected by password. Will let you know when it is done.

**Comment by anjesh** [comment] 2018-04-26 10:40
For ease, i have made the staging protected as well. Same previous credentials works admin@nrgi.com/password
Production should run once production site is created and branch pushed to master.

**Comment by adinuca** [comment] 2018-04-26 10:55
https://zambia.resourcecontracts.org has been set up. It is now serving the resourcecontracts.org site, but once the subsite gets to production,  the correct site will be served and it will be protected by password.

**Comment by adinuca** [comment] 2018-04-27 15:04
Hello, 

Just wanted to let you know that Staging was broken from the 23rd till the 26th of April due to the fact that the SSL certificate for the Elasticsearch node could not renew automatically. All has been fixed now. 
This is the message that we have received from Compose support, the Elasticsearch provider:

> The Let's Encrypt cert had failed to auto-renew. It shouldn't happen, but does sometimes. If it does you'll see a "Install Let's Encrypt" button in the UI you can try clicking that. If that fails to renew then we (support) have to manually renew it.
I've renewed this one already.

Production has not been affected by this issue and Staging has been back up since yesterday.

We will keep a closer eye on the logs  with the hope that we will catch this kinds if issues sooner.

Sorry for the inconvenience caused.

**Comment by charlesyoung** [comment] 2018-04-29 12:53
Thanks @adinuca 

When will the production site be operational?

**Comment by anjesh** [comment] 2018-05-02 12:39
https://zambia.resourcecontracts.org/ ready with credentials admin@nrgi.com/password

**Comment by anjesh** [comment] 2018-05-08 08:56
@adinuca could you please check if ELASTIC_SEARCH_HOST=http://api-staging.resourcecontracts.org is set in the staging instance or not?

**Comment by adinuca** [comment] 2018-05-08 09:06
Hi @anjesh , these 2 environment variables are set : 
```
 {
          "name": "ELASTIC_SEARCH_HOST",
          "value": "http://api-staging.resourcecontracts.org"
        },
        {
          "name": "GN_ELASTIC_SEARCH_HOST",
          "value": "http://api.resourcecontracts.org"
        }
```

**Comment by anjesh** [comment] 2018-05-08 09:15
Thanks @adinuca.

@charlesyoung Can you see if it's working?
http://api-staging.resourcecontracts.org/contracts?country_code=zm and http://api.resourcecontracts.org/contracts?country_code=zm gives 8 contracts. Let us know if the changes are reflected or not.

**Comment by charlesyoung** [comment] 2018-05-08 09:32
I don't see the change. Below doc shows on the staging RC global site but not on the staging country site. 

http://admin-staging.resourcecontracts.org/contract/2283

http://staging.resourcecontracts.org/search?q=&country%5B%5D=zm

**Comment by charlesyoung** [comment] 2018-05-08 14:42
Any luck looking at this issue? 

cc @anjesh @adinuca

**Comment by anjesh** [comment] 2018-05-08 15:50
@adinuca could you also set GN_ELASTIC_SEARCH_HOST to http://api-staging.resourcecontracts.org in staging server. It looks like that value of GN_ELASTIC_SEARCH_HOST is set as ELASTIC_SEARCH_HOST when .env for Zambia is created, hence it's showing the production numbers. 

tanzania staging is working though.

**Comment by adinuca** [comment] 2018-05-08 16:01
Hello, I will check first why this doesn't work. From the code it looks like it should be set to ELASTIC_SEARCH_HOST.

**Comment by adinuca** [comment] 2018-05-08 16:10
The issue is that .env for Zambia is generated after the one for Guinea, after setting ELASTIC_SEARCH_HOST to GN_ELASTIC_SEARCH_HOST. If you move the generation  of the .env for Zambia before the one for Guinea, it should work as expected. 
```
#country-guinea
export SERVER_NAME="guinea.resourcecontracts.org *.guinea.resourcecontracts.org contratsminiersguinee.org *.contratsminiersguinee.org"
export TRACKING_ID=${GN_TRACKING_ID}
export DB_DATABASE=${COUNTRY_DB_DATABASE}
export CONTACT_MAIL=${GN_CONTACT_MAIL}
export ELASTIC_SEARCH_HOST=${GN_ELASTIC_SEARCH_HOST}
export COUNTRY=gn

export CATEGORY=country-gn
envsubst '$SERVER_NAME $CATEGORY'< ./nginx_subsite.template > /etc/nginx/sites-enabled/country-gn

export CATEGORY=rc
envsubst < ./env.template > /var/www/country-gn/.env

#country-zambia
export SERVER_NAME="zambia.resourcecontracts.org *.zambia.resourcecontracts.org"
export TRACKING_ID=${ZM_TRACKING_ID}
export DB_DATABASE=${COUNTRY_DB_DATABASE}
export CONTACT_MAIL=${ZM_CONTACT_MAIL}
export COUNTRY=zm

export CATEGORY=country-zm
envsubst '$SERVER_NAME $CATEGORY'< ./nginx_subsite_protected.template > /etc/nginx/sites-enabled/country-zm

export CATEGORY=rc
envsubst < ./env.template > /var/www/country-zm/.env
```

**Comment by anjesh** [comment] 2018-05-08 16:19
thanks. It looks like production API was set for temporary testing in GN https://github.com/NRGI/resourcecontracts.org/issues/1077#issuecomment-345245172. I am going to remove `export ELASTIC_SEARCH_HOST=${GN_ELASTIC_SEARCH_HOST}` line from .env template and ZN staging should work.

**Comment by anjesh** [comment] 2018-05-08 16:41
http://staging.zambia.resourcecontracts.org/ count matches with api staging http://api-staging.resourcecontracts.org/contracts?country_code=zm 
@charlesyoung have a look

**Comment by charlesyoung** [comment] 2018-05-08 16:53
Thanks both, it's working.

**Closed** 2020-05-20 12:40 UTC
Labels: RC country request
