### ISSUE TITLE
Add view function for: draft / completed metadata in internal dashboard

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourcecontracts.org#184] opened 2015-08-10 15:07 UTC
As a researcher I need to be able to sellect/view all contracts that have not been approved/published. 

Currently I cannot view only the contracts which have: 
- not been published
- not had metadata marked as complete

This is needed as i want to go through this specifically.

**Comment by anderspeders** [comment] 2015-08-12 15:55
Unless anything has been done on this, I suggest that we push this to **blue sky**. 

We need to focus on the core bigger pieces for the moment.

**Comment by anjesh** [comment] 2015-08-26 08:07
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/212
Closing this.

**Closed by anjesh** 2015-08-26 08:07 UTC
Labels: enhancement / blue sky wish list
