### ISSUE TITLE
Adding an Associated Document

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#845] opened 2016-03-30 12:40 UTC
The document type is currently pulled from the main contract when adding an associated document. The document type needs to remain required but should be blank because the associated documents document type could be different form the main contracts document type. 

A question; the type of contract is currently also pulled from the main contract when adding an associated document. Will an associated document have a contract type?

**Comment by SamCCSI** [comment] 2016-03-30 13:55
@charlesyoung Associated documents can be contracts (in which case they will have a contract type).

**Comment by charlesyoung** [comment] 2016-03-30 14:00
OK thanks @SamCCSI. 

Do we then pull the main contracts contract type when adding an associated document or leave it blank?

**Comment by SamCCSI** [comment] 2016-03-30 15:57
@charlesyoung  I would leave it blank - more often than not contract type will be different for the main and associated document.

Eg. The main contract might be a concession agreement, and the associated document might be a MOU. For both, Doc type = Contract, but the contract type will vary.

**Comment by charlesyoung** [comment] 2016-03-31 07:48
When adding associated documents the following needs to change. 

1. Document type should be left **blank **and remain mandatory
2. Contract type should be left **blank **and remain non mandatory

**Comment by charlesyoung** [comment] 2016-04-28 09:40
@upasna01 I noticed that this ticket has been tagged as done. I however don't see the changes when adding an associated document.

**Comment by upasna01** [comment] 2016-04-29 11:09
The issue is fixed but not deployed, will be deployed soon. Thank You.

**Comment by upasna01** [comment] 2016-05-19 11:29
This issue is deployed, I think it can be closed for now. Please do verify..

**Comment by charlesyoung** [comment] 2016-05-19 13:02
Document type needs to be left blank and remain mandatory. The associated document currently still pulls the main contracts document type.

**Comment by upasna01** [comment] 2016-06-16 12:18
The issue is fixed now, please do verify.

http://admin.resourcecontracts.org/contract/create?parent=101
![832](https://cloud.githubusercontent.com/assets/11477899/16116420/9983842e-33ec-11e6-8e3a-a2db17fec4de.png)

**Closed by upasna01** 2016-06-16 12:18 UTC
Labels: 3 - Done, Country requests, Metadata
