### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by charlesyoung** [NRGI/resourcecontracts.org#477] opened 2015-10-06 13:31 UTC
Will the RC site include multilingual support? 

[A question from the Pretoria Workshop]

**Comment by anjesh** [comment] 2016-01-18 06:08
We will have multi lingual support. 
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/47

**Closed by anjesh** 2016-01-18 06:08 UTC
Labels: question
