### ISSUE TITLE
Search functionality 

### ISSUE THREAD

**Issue by JesseCCSI** [NRGI/resourcecontracts.org#620] opened 2015-10-30 19:43 UTC
When you search for a term, the search results are currently not prioritized in a way that is helpful to the user (unless you use boolean searches)

Taking the Global Agricultural Development (Cambodia) Ltd contract as an example:
1. User searches for company name as "Global Agricultural Development"
2. The correct result only shows up on the third page of search results (4th result from the bottom of the page)

![global ag page 3 search results](https://cloud.githubusercontent.com/assets/14910764/10856259/dd2d7b38-7f1c-11e5-990f-cc1aba882eba.png)

Maybe this is happening because the search function currently prioritizes based on the frequency of the terms used in the text of the contracts? This is problematic because many company names also include common terms that will also be in the contract (e.g. "agricultural" or "logging").

We can make it clear in the FAQ section that users should use "..." when searching for a phrase, but I wonder whether there's a way to better prioritise the results as well (as many users won't read the FAQ page)? 

Many thanks.

**Comment by charlesyoung** [comment] 2015-11-02 11:50
Linked to RC Searching Results #458

**Comment by anjesh** [comment] 2016-01-15 11:10
Duplicate of https://github.com/NRGI/resourcecontracts.org/issues/458

**Closed by anjesh** 2016-01-15 11:10 UTC
