### ISSUE TITLE
UX Unpredictable display of text/annotation searching results

### ISSUE THREAD

**Issue by SamCCSI** [NRGI/resourcecontracts.org#887] opened 2016-05-18 20:49 UTC
If I search for "consent" the results show me one text result and one annotation result containing that term. And I can click on the text which takes me directly to that search result. This works well.

![image](https://cloud.githubusercontent.com/assets/12913915/15374375/0d9521ce-1d18-11e6-937d-aa43ab573904.png)

BUT If I search for "stablization" it shows the contracts containing the term only, but no text excerpts.
![image](https://cloud.githubusercontent.com/assets/12913915/15374435/648d18d8-1d18-11e6-8dd0-674514118f11.png)

**Comment by upasna01** [comment] 2016-06-30 07:47
The issue is fixed now, please do verify.

**Comment by SamCCSI** [comment] 2016-07-01 13:41
This is strange. I'm now getting zero results for search of stabilization http://www.openlandcontracts.org/search?q=stabilization

![image](https://cloud.githubusercontent.com/assets/12913915/16523158/e4b58224-3f6f-11e6-8690-353577377653.png)

**Comment by KaitlinCCSI** [comment] 2016-07-01 14:19
Note that we are doing a training using this site next week, so hopefully this can be addressed soon.

**Comment by hello-deepak** [comment] 2016-07-04 05:51
The query of "text string" searches in metadata, pdf text and annotations text .

![admin resource contracts](https://cloud.githubusercontent.com/assets/12913915/15374435/648d18d8-1d18-11e6-8dd0-674514118f11.png)
We got this result, because we have flaws in our search . It was also actually searching in annotation category as well which should not be, so now it is fixed and only searches in annotation text. 


>This is strange. I'm now getting zero results for search of stabilization http://www.openlandcontracts.org/search?q=stabilization

And when on searching http://www.openlandcontracts.org/search?q=stabilization we got zero results because there is no "stabilization" word in metadata, pdf text or annotations text .

**Comment by hello-deepak** [comment] 2016-07-15 05:10
@SamCCSI @KaitlinCCSI 
Any update?

**Comment by SamCCSI** [comment] 2016-07-15 13:38
@hello-deepak apologies for the delay. Is it possible to re-include annotation category titles in the searchable text field?

This is important because some users might want to quickly search for terms like stabilization, but may not take the time to learn that they can scroll through annotation categories.

**Comment by hello-deepak** [comment] 2016-10-03 08:47
Fixed .
Now, Annotation category is also searchable from text search .

![unpredict](https://cloud.githubusercontent.com/assets/7577697/19031801/ee8f6a4e-8975-11e6-8556-a1bfebff0bc6.png)

**Closed by hello-deepak** 2016-10-03 08:47 UTC
Labels: bug
